-- ============================================================
-- SEED DÉMO Piscine Max (multi-tenant) — mot de passe : piscine
-- Réinitialise toutes les données de démonstration.
-- ============================================================
DELETE FROM photos;
DELETE FROM maintenance_logs;
DELETE FROM maintenances;
DELETE FROM pool_seasons;
DELETE FROM pools;
DELETE FROM clients;
DELETE FROM pro_workers;
DELETE FROM procedures;
DELETE FROM users;
DELETE FROM sqlite_sequence WHERE name IN ('users','clients','pools','maintenances','maintenance_logs','pro_workers','photos','pool_seasons','procedures');

INSERT INTO users (id, email, password_hash, name, role, color, company, phone, created_by) VALUES (1, 'franck@piscine-max.fr', 'pbkdf2$100000$46db0de1cd98a38c9119430cb5502c73$ecc58d3248b0798a28fbe0c9e964a23369baae71b44b6881cfbd0fe600491310', 'Franck', 'member', '#0891b2', 'Piscine Max', '06 12 34 56 78', NULL);
INSERT INTO users (id, email, password_hash, name, role, color, company, phone, created_by) VALUES (2, 'romain@piscine-max.fr', 'pbkdf2$100000$fc96c96673d274275069cb4bb4a30cc0$3c7592ad0c29d3882048a8e9c7575a843c70b55cc8d20f78351df61542b7b1ab', 'Romain', 'member', '#16a34a', NULL, '06 98 76 54 32', 1);
INSERT INTO users (id, email, password_hash, name, role, color, company, phone, created_by) VALUES (3, 'sophie@aquazur.fr', 'pbkdf2$100000$3066dce2c00c2d824b8c2093ec522e04$08f51ca421a15f75e9b61abfcd057c0a7f6a6fb83e0f9b3e3b103ca11cb2d266', 'Sophie Marin', 'member', '#8b5cf6', 'AquaZur', '06 11 22 33 44', NULL);
INSERT INTO users (id, email, password_hash, name, role, color, company, phone, created_by) VALUES (4, 'leo@aquazur.fr', 'pbkdf2$100000$57dfcb905622b9e35a6b47af52404c2b$5e0b129ebe2b94ced0048ce989cffaadbabfa7075a1579c765c27bdd62d03123', 'Léo', 'member', '#f59e0b', NULL, '06 55 66 77 88', 3);
INSERT INTO users (id, email, password_hash, name, role, color, company, phone, created_by) VALUES (5, 'client1@piscine-max.fr', 'pbkdf2$100000$21d365a29989493c1033bcf02695f437$10c11d43f3fc5991ac4c519a0de86beb888686d48d559868fe9e440eea2fe654', 'Famille Dubois', 'client', '#64748b', NULL, NULL, 1);
INSERT INTO users (id, email, password_hash, name, role, color, company, phone, created_by) VALUES (6, 'client2@piscine-max.fr', 'pbkdf2$100000$524cb93382fb8c4d2d6c95c543e0badd$12eb32b8d57bbf6cad01965073fe9c77f683c39279e3ce558d1c768f5408311c', 'M. Lefevre', 'client', '#64748b', NULL, NULL, 1);

INSERT INTO pro_workers (pro_id, worker_id) VALUES (1, 2);  -- Romain bosse pour Franck
INSERT INTO pro_workers (pro_id, worker_id) VALUES (3, 4);  -- Léo bosse pour Sophie
INSERT INTO pro_workers (pro_id, worker_id) VALUES (3, 2);  -- Romain bosse AUSSI pour Sophie (un user, 2 employeurs)

INSERT INTO clients (id, name, phone, email, notes, owner_id, client_user_id) VALUES (1, 'Famille Dubois', '06 20 11 22 33', 'client1@piscine-max.fr', 'Maison avec grand portail bleu. Sonner 2 fois.', 1, 5);
INSERT INTO clients (id, name, phone, email, notes, owner_id, client_user_id) VALUES (2, 'M. Lefevre', '06 30 44 55 66', 'client2@piscine-max.fr', 'Résidence secondaire, présent surtout l''été.', 1, 6);
INSERT INTO clients (id, name, phone, email, notes, owner_id, client_user_id) VALUES (3, 'Villa Les Mimosas', '04 94 00 11 22', 'contact@lesmimosas.fr', 'Location saisonnière, 2 piscines à entretenir.', 1, NULL);
INSERT INTO clients (id, name, phone, email, notes, owner_id, client_user_id) VALUES (4, 'Restaurant La Plage', '04 94 33 44 55', 'resa@laplage.fr', 'Piscine du restaurant, entretien tôt le matin avant ouverture.', 1, NULL);
INSERT INTO clients (id, name, phone, email, notes, owner_id, client_user_id) VALUES (5, 'M. et Mme Garcia', '06 77 88 99 00', 'garcia@exemple.fr', 'Client de Sophie.', 3, NULL);
INSERT INTO clients (id, name, phone, email, notes, owner_id, client_user_id) VALUES (6, 'Camping Le Pin', '04 94 99 88 77', 'camping@lepin.fr', 'Grande piscine collective.', 3, NULL);

INSERT INTO pools (id, client_id, owner_id, label, address, lat, lng, pool_type, volume_m3, shape, treatment_type, filtration_type, access_code, access_notes, routine, routine_client, ideal_ph_min, ideal_ph_max, ideal_chlorine_min, ideal_chlorine_max, priority, ideal_salt_min, ideal_salt_max, ideal_tac_min, ideal_tac_max, ideal_stabilizer_min, ideal_stabilizer_max, depth_avg_m, expected_interval_days) VALUES (1, 1, 1, 'Piscine principale', '12 Chemin des Oliviers, 83110 Sanary-sur-Mer', 43.1287, 5.8011, 'enterrée', 48, 'rectangulaire', 'sel/électrolyse', 'sable', 'B1234', 'Portail bleu, local technique au fond du jardin à droite. Chien gentil.', '["Vérifier le niveau d''eau","Nettoyer les skimmers et le préfiltre","Tester pH et chlore","Brosser les parois","Contrôler la pression du filtre"]', 'Passez le robot 1 à 2 fois par semaine. Maintenez le niveau d''eau à la moitié des skimmers. Évitez de vous baigner dans les 4h après un ajout de produit.', 7, 7.4, 1, 2, 1, 3.0, 5.0, 80, 120, 30, 50, 1.5, 7);
INSERT INTO pools (id, client_id, owner_id, label, address, lat, lng, pool_type, volume_m3, shape, treatment_type, filtration_type, access_code, access_notes, routine, routine_client, ideal_ph_min, ideal_ph_max, ideal_chlorine_min, ideal_chlorine_max, priority, ideal_salt_min, ideal_salt_max, ideal_tac_min, ideal_tac_max, ideal_stabilizer_min, ideal_stabilizer_max, depth_avg_m, expected_interval_days) VALUES (2, 2, 1, 'Piscine', '45 Avenue de la Mer, 83140 Six-Fours-les-Plages', 43.0942, 5.8389, 'coque', 32, 'haricot', 'chlore', 'cartouche', '', 'Clé sous le pot de fleurs près de la porte de garage.', '["Tester pH et chlore","Nettoyer la ligne d''eau","Vider les paniers"]', 'Surveillez la couleur de l''eau. En cas d''eau trouble, appelez-moi.', 7, 7.4, 1.5, 3, 0, 3.0, 5.0, 80, 120, 30, 50, 1.5, 7);
INSERT INTO pools (id, client_id, owner_id, label, address, lat, lng, pool_type, volume_m3, shape, treatment_type, filtration_type, access_code, access_notes, routine, routine_client, ideal_ph_min, ideal_ph_max, ideal_chlorine_min, ideal_chlorine_max, priority, ideal_salt_min, ideal_salt_max, ideal_tac_min, ideal_tac_max, ideal_stabilizer_min, ideal_stabilizer_max, depth_avg_m, expected_interval_days) VALUES (3, 3, 1, 'Grande piscine', '8 Route de Bandol, 83150 Bandol', 43.1355, 5.7531, 'béton', 75, 'rectangulaire', 'sel/électrolyse', 'sable', 'C5678', 'Code portail C5678. Piscine côté terrasse.', '["Analyse complète de l''eau","Nettoyage robot","Backwash filtre","Contrôle électrolyseur"]', '', 7.2, 7.6, 1, 2, 1, 3.0, 5.0, 80, 120, 30, 50, 1.5, 7);
INSERT INTO pools (id, client_id, owner_id, label, address, lat, lng, pool_type, volume_m3, shape, treatment_type, filtration_type, access_code, access_notes, routine, routine_client, ideal_ph_min, ideal_ph_max, ideal_chlorine_min, ideal_chlorine_max, priority, ideal_salt_min, ideal_salt_max, ideal_tac_min, ideal_tac_max, ideal_stabilizer_min, ideal_stabilizer_max, depth_avg_m, expected_interval_days) VALUES (4, 3, 1, 'Petit bassin', '8 Route de Bandol, 83150 Bandol', 43.1358, 5.7535, 'béton', 18, 'carrée', 'chlore', 'cartouche', 'C5678', 'Même accès que la grande piscine.', '["Tester pH et chlore","Nettoyer le bassin"]', '', 7, 7.4, 1, 2, 0, 3.0, 5.0, 80, 120, 30, 50, 1.5, 7);
INSERT INTO pools (id, client_id, owner_id, label, address, lat, lng, pool_type, volume_m3, shape, treatment_type, filtration_type, access_code, access_notes, routine, routine_client, ideal_ph_min, ideal_ph_max, ideal_chlorine_min, ideal_chlorine_max, priority, ideal_salt_min, ideal_salt_max, ideal_tac_min, ideal_tac_max, ideal_stabilizer_min, ideal_stabilizer_max, depth_avg_m, expected_interval_days) VALUES (5, 4, 1, 'Piscine restaurant', '2 Promenade du Front de Mer, 83110 Sanary-sur-Mer', 43.1201, 5.7998, 'enterrée', 60, 'libre', 'sel/électrolyse', 'verre', 'RESTO', 'Entrée par l''arrière, avant 9h. Demander au gérant.', '["Analyse eau","Nettoyage complet","Vérifier propreté plages"]', '', 7, 7.4, 1.5, 2.5, 1, 3.0, 5.0, 80, 120, 30, 50, 1.5, 7);
INSERT INTO pools (id, client_id, owner_id, label, address, lat, lng, pool_type, volume_m3, shape, treatment_type, filtration_type, access_code, access_notes, routine, routine_client, ideal_ph_min, ideal_ph_max, ideal_chlorine_min, ideal_chlorine_max, priority, ideal_salt_min, ideal_salt_max, ideal_tac_min, ideal_tac_max, ideal_stabilizer_min, ideal_stabilizer_max, depth_avg_m, expected_interval_days) VALUES (6, 5, 3, 'Piscine Garcia', '15 Rue des Lauriers, 83000 Toulon', 43.1242, 5.928, 'enterrée', 40, 'ovale', 'chlore', 'sable', '9012', 'Portail vert.', '["pH chlore","Skimmers"]', '', 7, 7.4, 1, 2, 0, 3.0, 5.0, 80, 120, 30, 50, 1.5, 7);
INSERT INTO pools (id, client_id, owner_id, label, address, lat, lng, pool_type, volume_m3, shape, treatment_type, filtration_type, access_code, access_notes, routine, routine_client, ideal_ph_min, ideal_ph_max, ideal_chlorine_min, ideal_chlorine_max, priority, ideal_salt_min, ideal_salt_max, ideal_tac_min, ideal_tac_max, ideal_stabilizer_min, ideal_stabilizer_max, depth_avg_m, expected_interval_days) VALUES (7, 6, 3, 'Piscine camping', '100 Route des Pins, 83270 Saint-Cyr-sur-Mer', 43.18, 5.71, 'béton', 120, 'rectangulaire', 'sel/électrolyse', 'sable', 'CAMP', 'Voir réception.', '["Analyse","Robot","Backwash"]', '', 7.2, 7.6, 1.5, 3, 1, 3.0, 5.0, 80, 120, 30, 50, 1.5, 7);

INSERT INTO maintenances (id, pool_id, assigned_to, kind, weekday, interval_weeks, start_date, time, duration_min, notes) VALUES (1, 1, 2, 'recurring', 2, 1, '2025-01-01', '09:00', 45, 'Entretien hebdo');
INSERT INTO maintenances (id, pool_id, assigned_to, kind, weekday, interval_weeks, start_date, time, duration_min, notes) VALUES (2, 2, 1, 'recurring', 3, 2, '2025-01-01', '10:30', 30, 'Toutes les 2 semaines');
INSERT INTO maintenances (id, pool_id, assigned_to, kind, weekday, interval_weeks, start_date, time, duration_min, notes) VALUES (3, 3, 2, 'recurring', 2, 1, '2025-01-01', '11:00', 60, '');
INSERT INTO maintenances (id, pool_id, assigned_to, kind, weekday, interval_weeks, start_date, time, duration_min, notes) VALUES (4, 4, 2, 'recurring', 2, 1, '2025-01-01', '12:15', 20, 'Juste après la grande');
INSERT INTO maintenances (id, pool_id, assigned_to, kind, weekday, interval_weeks, start_date, time, duration_min, notes) VALUES (5, 5, 1, 'recurring', 5, 1, '2025-01-01', '07:30', 45, 'Avant ouverture resto');
INSERT INTO maintenances (id, pool_id, assigned_to, kind, oneshot_date, time, duration_min, notes) VALUES (6, 1, 1, 'oneshot', '2026-07-08', '14:00', 60, 'Hivernage');
INSERT INTO maintenances (id, pool_id, assigned_to, kind, weekday, interval_weeks, start_date, time, duration_min, notes) VALUES (7, 6, 4, 'recurring', 1, 1, '2025-01-01', '09:00', 30, '');
INSERT INTO maintenances (id, pool_id, assigned_to, kind, weekday, interval_weeks, start_date, time, duration_min, notes) VALUES (8, 7, 4, 'recurring', 4, 1, '2025-01-01', '08:00', 90, '');

INSERT INTO pool_seasons (pool_id, label, start_md, end_md, interval_days, weekday, sort_order, active) VALUES (1, 'Haute saison', '06-01', '09-15', 3, NULL, 0, 1);
INSERT INTO pool_seasons (pool_id, label, start_md, end_md, interval_days, weekday, sort_order, active) VALUES (1, 'Mi-saison', '04-01', '05-31', 7, NULL, 1, 1);
INSERT INTO pool_seasons (pool_id, label, start_md, end_md, interval_days, weekday, sort_order, active) VALUES (1, 'Automne', '09-16', '10-31', 7, NULL, 2, 1);
INSERT INTO pool_seasons (pool_id, label, start_md, end_md, interval_days, weekday, sort_order, active) VALUES (1, 'Hivernage', '11-01', '03-31', 30, NULL, 3, 1);
INSERT INTO pool_seasons (pool_id, label, start_md, end_md, interval_days, weekday, sort_order, active) VALUES (5, 'Pleine saison resto', '05-15', '09-30', 2, NULL, 0, 1);
INSERT INTO pool_seasons (pool_id, label, start_md, end_md, interval_days, weekday, sort_order, active) VALUES (5, 'Hors saison', '10-01', '05-14', 14, NULL, 1, 1);

INSERT INTO maintenance_logs (id, maintenance_id, done_by, done_date, status, ph, chlorine, salt, water_temp, stabilizer, tac, products_added, notes, duration_min) VALUES (1, 1, 2, '2026-05-08', 'done', 7.6, 0.4, 4.2, 27, 35, 110, 'pH- 1L, chlore choc 500g', 'pH un peu haut, corrigé', 45);
INSERT INTO maintenance_logs (id, maintenance_id, done_by, done_date, status, ph, chlorine, salt, water_temp, stabilizer, tac, products_added, notes, duration_min) VALUES (2, 1, 2, '2026-05-15', 'done', 7.5, 0.6, 4.1, 27, 35, 105, 'pH- 0.5L', 'RAS', 45);
INSERT INTO maintenance_logs (id, maintenance_id, done_by, done_date, status, ph, chlorine, salt, water_temp, stabilizer, tac, products_added, notes, duration_min) VALUES (3, 1, 2, '2026-05-22', 'done', 7.3, 1.2, 4, 26, 32, 100, NULL, 'Eau nickel', 45);
INSERT INTO maintenance_logs (id, maintenance_id, done_by, done_date, status, ph, chlorine, salt, water_temp, stabilizer, tac, products_added, notes, duration_min) VALUES (4, 1, 2, '2026-05-29', 'done', 7.2, 1.5, 4, 26, 30, 100, NULL, 'RAS', 45);
INSERT INTO maintenance_logs (id, maintenance_id, done_by, done_date, status, ph, chlorine, salt, water_temp, stabilizer, tac, products_added, notes, duration_min) VALUES (5, 1, 2, '2026-06-05', 'done', 7.2, 1.6, 3.9, 25, 30, 98, NULL, 'Filtre nettoyé', 45);
INSERT INTO maintenance_logs (id, maintenance_id, done_by, done_date, status, ph, chlorine, salt, water_temp, stabilizer, tac, products_added, notes, duration_min) VALUES (6, 1, 2, '2026-06-12', 'done', 7.1, 1.8, 4, 24, 28, 95, NULL, 'RAS', 45);
INSERT INTO maintenance_logs (id, maintenance_id, done_by, done_date, status, ph, chlorine, salt, water_temp, stabilizer, tac, products_added, notes, duration_min) VALUES (7, 1, 2, '2026-06-19', 'done', 7.2, 1.7, 4, 23, 30, 100, NULL, 'RAS', 45);
INSERT INTO maintenance_logs (id, maintenance_id, done_by, done_date, status, ph, chlorine, salt, water_temp, stabilizer, tac, products_added, notes, duration_min) VALUES (8, 1, 2, '2026-06-30', 'done', 7.9, 0.4, 4, 29, 30, 100, NULL, 'Forte chaleur, chlore consommé — à resurveiller', 45);
INSERT INTO maintenance_logs (id, maintenance_id, done_by, done_date, status, ph, chlorine, salt, water_temp, stabilizer, tac, products_added, notes, duration_min) VALUES (9, 3, 2, '2026-06-05', 'done', 7.8, 0.8, 4.5, 27, 40, 120, 'pH- 2L', 'pH haut', 45);
INSERT INTO maintenance_logs (id, maintenance_id, done_by, done_date, status, ph, chlorine, salt, water_temp, stabilizer, tac, products_added, notes, duration_min) VALUES (10, 3, 2, '2026-06-12', 'done', 7.5, 1.4, 4.3, 26, 38, 110, NULL, 'RAS', 45);
INSERT INTO maintenance_logs (id, maintenance_id, done_by, done_date, status, ph, chlorine, salt, water_temp, stabilizer, tac, products_added, notes, duration_min) VALUES (11, 3, 2, '2026-06-19', 'done', 7.4, 1.6, 4.2, 25, 35, 105, NULL, 'RAS', 45);
INSERT INTO maintenance_logs (id, maintenance_id, done_by, done_date, status, ph, chlorine, salt, water_temp, stabilizer, tac, products_added, notes, duration_min) VALUES (12, 3, 2, '2026-06-26', 'done', 7.3, 1.8, 4.2, 24, 35, 100, NULL, 'Backwash effectué', 45);
INSERT INTO maintenance_logs (id, maintenance_id, done_by, done_date, status, ph, chlorine, salt, water_temp, stabilizer, tac, products_added, notes, duration_min) VALUES (13, 2, 1, '2026-06-23', 'done', 7.3, 1.5, NULL, 25, 30, 90, NULL, 'RAS', 45);
INSERT INTO maintenance_logs (id, maintenance_id, done_by, done_date, status, ph, chlorine, salt, water_temp, stabilizer, tac, products_added, notes, duration_min) VALUES (14, 2, 1, '2026-06-09', 'done', 7.4, 1.2, NULL, 24, 30, 90, 'Chlore lent 1kg', 'Recharge galets', 45);

INSERT INTO procedures (id, owner_id, created_by, type, title, category, summary, content, tags) VALUES (1, 1, 1, 'procedure', 'Changer le préfiltre de la pompe', 'Filtration', 'Nettoyer ou remplacer le panier du préfiltre pompe.', '1. Couper l''alimentation électrique de la pompe.
2. Fermer les vannes d''aspiration si présentes.
3. Dévisser et retirer le couvercle transparent du préfiltre.
4. Sortir le panier, le vider et le rincer au jet.
5. Vérifier l''état du joint torique, le graisser légèrement si besoin.
6. Remettre le panier, refermer le couvercle, réamorcer la pompe (remplir d''eau avant de redémarrer).
7. Rouvrir les vannes puis remettre sous tension.', 'préfiltre, pompe, filtration, panier');
INSERT INTO procedures (id, owner_id, created_by, type, title, category, summary, content, tags) VALUES (2, 1, 1, 'procedure', 'Changer le sable du filtre à sable', 'Filtration', 'Remplacement complet de la charge de sable du filtre, à faire tous les 5 à 7 ans.', '1. Couper la pompe et mettre la vanne multivoie sur "Fermé".
2. Vidanger la cuve du filtre (vanne de vidange ou tuyau).
3. Ouvrir la trappe supérieure et retirer l''ancien sable à l''aide d''une pelle/aspirateur à sable (attention à ne pas abîmer la crépine centrale).
4. Rincer soigneusement la cuve.
5. Verser un fond d''eau, puis remplir avec le sable neuf (granulométrie adaptée) jusqu''au niveau indiqué par le fabricant.
6. Refermer la trappe, mettre la vanne sur "Lavage" (backwash) 2-3 minutes.
7. Passer en "Rinçage" 30 secondes, puis repasser en "Filtration".', 'filtre à sable, backwash, filtration, entretien annuel');
INSERT INTO procedures (id, owner_id, created_by, type, title, category, summary, content, tags) VALUES (3, 1, 1, 'procedure', 'Choc chlore (traitement choc)', 'Traitement de l''eau', 'Procédure à appliquer en cas d''eau trouble, verte ou après une forte affluence.', '1. Tester le pH et le ramener entre 7.2 et 7.4 avant le choc.
2. Calculer la dose de chlore choc selon le volume du bassin (voir dosage produit).
3. Diluer le chlore choc dans un seau d''eau si c''est un produit en poudre/granulés.
4. Verser progressivement au bord du bassin, filtration en marche.
5. Laisser tourner la filtration en continu au moins 24h.
6. Ne pas se baigner tant que le taux de chlore n''est pas redescendu sous 3 mg/L.
7. Recontrôler pH et chlore le lendemain et ajuster.', 'chlore choc, eau trouble, eau verte, désinfection');
INSERT INTO procedures (id, owner_id, created_by, type, title, category, summary, content, tags) VALUES (4, 1, 1, 'procedure', 'Hivernage d''une piscine', 'Hivernage / Estivage', 'Mise en hivernage passif ou actif avant l''arrêt saisonnier.', '1. Nettoyer soigneusement le bassin (brossage parois + fond, aspiration).
2. Équilibrer l''eau (pH 7.2-7.4, TAC correct) et faire un traitement choc.
3. Ajouter un produit d''hivernage adapté au traitement (chlore, sel, brome...).
4. Baisser le niveau d''eau sous les skimmers (hivernage passif) ou laisser tourner la filtration au ralenti (hivernage actif, climat doux).
5. Vider les canalisations exposées au gel, poser les gizzmos/flotteurs anti-gel dans skimmers et refoulements.
6. Démonter, vidanger et stocker au sec la pompe et le filtre si hivernage passif complet.
7. Couvrir le bassin (bâche d''hivernage ou volet).', 'hivernage, gel, fermeture saisonnière');
INSERT INTO procedures (id, owner_id, created_by, type, title, category, summary, content, tags) VALUES (5, 1, 2, 'procedure', 'Remise en route au printemps', 'Hivernage / Estivage', 'Réouverture de la piscine après hivernage.', '1. Retirer la bâche/volet d''hivernage, la nettoyer avant stockage.
2. Retirer les gizzmos et remonter pompe/filtre si démontés.
3. Remonter le niveau d''eau au-dessus des skimmers.
4. Nettoyer le bassin (brossage, aspiration des feuilles et dépôts hivernaux).
5. Faire un backwash complet du filtre avant remise en route.
6. Relancer la filtration en continu 24-48h.
7. Tester et rééquilibrer TAC, pH puis chlore ; refaire un choc si l''eau est trouble.', 'remise en route, printemps, réouverture');
INSERT INTO procedures (id, owner_id, created_by, type, title, category, summary, content, tags) VALUES (6, 1, 2, 'procedure', 'Pompe qui ne s''amorce plus', 'Dépannage matériel', 'Diagnostic rapide en cas de pompe qui tourne mais n''aspire pas l''eau.', '1. Vérifier qu''il n''y a pas de prise d''air : contrôler le joint du couvercle du préfiltre et le niveau d''eau du bassin.
2. Nettoyer le panier du préfiltre s''il est colmaté.
3. Vérifier que les vannes d''aspiration sont bien ouvertes.
4. Remplir le préfiltre d''eau manuellement pour réamorcer, remettre le couvercle, redémarrer.
5. Si toujours rien : contrôler le clapet anti-retour et la canalisation d''aspiration pour une fuite d''air.
6. Si le souci persiste, vérifier l''état de la turbine et du moteur (bruit anormal, échauffement).', 'pompe, amorçage, panne, dépannage');
INSERT INTO procedures (id, owner_id, created_by, type, title, category, summary, content, tags) VALUES (7, 3, 3, 'procedure', 'Contrôle électrolyseur au sel', 'Traitement de l''eau', 'Vérification mensuelle d''une installation de traitement au sel.', '1. Vérifier le taux de sel avec un testeur dédié (cible générale 3 à 5 g/L, voir notice du bassin).
2. Contrôler les cellules de l''électrolyseur : détartrer si dépôt blanchâtre visible.
3. Vérifier l''affichage du boîtier (% de production, alarme éventuelle).
4. Ajuster la production selon la température de l''eau et la fréquentation.
5. Recontrôler pH et chlore générés après réglage.', 'sel, électrolyseur, cellule, détartrage');
INSERT INTO procedures (id, owner_id, created_by, type, title, category, summary, content, tags) VALUES (8, 3, 3, 'procedure', 'Nettoyage de la ligne d''eau', 'Nettoyage', 'Retirer les traces de calcaire, graisses et pollens à la ligne de flottaison.', '1. Baisser légèrement le niveau d''eau si les traces sont importantes.
2. Utiliser un nettoyant spécial ligne d''eau adapté au revêtement (liner, carrelage, coque).
3. Frotter avec une éponge non abrasive ou une pierre à récurer pour le carrelage.
4. Rincer abondamment pour ne pas polluer l''eau du bassin.
5. Remettre le niveau d''eau au bon repère.', 'ligne d''eau, calcaire, nettoyage, esthétique');
INSERT INTO procedures (id, owner_id, created_by, type, title, category, summary, content, tags) VALUES (9, 1, 1, 'procedure', 'Nettoyer et détartrer un filtre à cartouche', 'Filtration', 'Entretien régulier de la ou des cartouches filtrantes.', '1. Couper la pompe et fermer les vannes si présentes.
2. Ouvrir la cuve du filtre et sortir la ou les cartouches.
3. Rincer au jet d''eau en insistant entre les plis, du haut vers le bas.
4. Si la cartouche est encrassée ou entartrée, la tremper une nuit dans un bain de détartrant/dégraissant spécial cartouche.
5. Rincer à nouveau abondamment avant remontage.
6. Vérifier l''état du joint de cuve, le remplacer si craquelé.
7. Remonter, réamorcer la pompe et relancer la filtration.
8. Prévoir le remplacement complet de la cartouche tous les 2 à 3 ans ou dès qu''elle est déformée/percée.', 'cartouche, filtre, détartrage, nettoyage');
INSERT INTO procedures (id, owner_id, created_by, type, title, category, summary, content, tags) VALUES (10, 1, 2, 'procedure', 'Recharger un filtre à diatomées', 'Filtration', 'Nettoyage des éléments filtrants et rechargement en terre de diatomées.', '1. Couper la pompe, fermer les vannes, mettre la vanne multivoie sur "Vidange".
2. Vidanger la cuve et retirer les grilles (éléments filtrants).
3. Rincer soigneusement les éléments filtrants au jet, en éliminant tous les résidus de terre de diatomées.
4. Vérifier l''état des toiles/grilles et les remplacer si déchirées.
5. Remonter les éléments, refermer la cuve.
6. Mettre en "Filtration", démarrer la pompe et introduire la nouvelle charge de diatomées par le skimmer, dosée selon la surface filtrante du filtre (voir notice fabricant).
7. Vérifier que l''eau ressort claire avant de considérer l''opération terminée.', 'diatomées, filtre, rechargement, précoat');
INSERT INTO procedures (id, owner_id, created_by, type, title, category, summary, content, tags) VALUES (11, 1, 1, 'procedure', 'Purger l''air et réamorcer le circuit de filtration', 'Filtration', 'À faire après toute intervention sur le circuit hydraulique ou en cas de prise d''air.', '1. Couper la pompe et fermer les vannes d''aspiration/refoulement.
2. Ouvrir le purgeur d''air du filtre (vis ou bouchon sur le dessus de la cuve).
3. Remplir le préfiltre de la pompe avec de l''eau avant de refermer le couvercle.
4. Rouvrir les vannes, remettre la pompe sous tension.
5. Laisser le purgeur ouvert jusqu''à ce qu''un filet d''eau continu (sans air) en sorte, puis le refermer.
6. Vérifier la pression au manomètre : une pression normale confirme l''amorçage réussi.
7. Si l''air revient en continu, rechercher une prise d''air (joint de préfiltre, raccord, niveau d''eau du bassin insuffisant).', 'amorçage, purge, air, circuit hydraulique');
INSERT INTO procedures (id, owner_id, created_by, type, title, category, summary, content, tags) VALUES (12, 1, 2, 'procedure', 'Nettoyer le panier du skimmer', 'Filtration', 'Entretien hebdomadaire de base, à faire plus souvent en période de feuilles/pollens.', '1. Couper la filtration.
2. Ouvrir le couvercle du skimmer et retirer le panier.
3. Vider les débris et rincer le panier au jet.
4. Vérifier le clapet anti-retour (volet) situé au fond du skimmer.
5. Vérifier le joint du couvercle et l''état du skimmer (fissures).
6. Remettre le panier en place, refermer le couvercle, relancer la filtration.
7. À faire au minimum une fois par semaine en pleine saison.', 'skimmer, panier, entretien hebdomadaire');
INSERT INTO procedures (id, owner_id, created_by, type, title, category, summary, content, tags) VALUES (13, 1, 1, 'procedure', 'Contrôler et purger la pression du filtre', 'Filtration', 'Surveillance du manomètre pour anticiper le colmatage du filtre.', '1. Relever la pression au manomètre en filtration normale (valeur de référence à noter dès l''installation, ex. 0,6 à 0,8 bar).
2. Si la pression a augmenté de 0,2 à 0,3 bar par rapport à la valeur de référence, le filtre est encrassé : procéder à un lavage (backwash pour sable/diatomées, nettoyage pour cartouche).
3. Si la pression est anormalement basse, vérifier qu''il n''y a pas de manque de débit en amont (préfiltre bouché, vanne fermée).
4. Après un backwash, purger l''air résiduel du filtre via le purgeur avant de remettre en filtration.
5. Noter la pression après nettoyage pour garder une référence à jour.', 'pression, manomètre, backwash, filtre');
INSERT INTO procedures (id, owner_id, created_by, type, title, category, summary, content, tags) VALUES (14, 1, 2, 'procedure', 'Rattraper une eau verte', 'Traitement de l''eau', 'Protocole complet de traitement curatif contre les algues vertes.', '1. Analyser pH, TAC et chlore avant toute intervention.
2. Ramener le pH entre 7.0 et 7.4 (l''eau verte fait souvent suite à un pH mal réglé ou un manque de chlore).
3. Brosser énergiquement parois et fond pour décoller les algues.
4. Faire un traitement choc au chlore non stabilisé (dose renforcée selon le volume, voir fiche dosage).
5. Laisser tourner la filtration en continu 24 à 48h, nettoyer le filtre à mi-parcours si la pression grimpe vite.
6. Aspirer les dépôts d''algues mortes au fond à l''évacuation (pas à travers le filtre si les dépôts sont importants).
7. Recontrôler chlore et pH le lendemain, renouveler le choc si l''eau reste trouble.', 'eau verte, algues, choc chlore, rattrapage');
INSERT INTO procedures (id, owner_id, created_by, type, title, category, summary, content, tags) VALUES (15, 1, 1, 'procedure', 'Rattraper une eau trouble ou laiteuse (floculation)', 'Traitement de l''eau', 'Clarification d''une eau trouble par floculation.', '1. Vérifier et équilibrer pH (7.2-7.4) et chlore avant floculation (le floculant est inefficace si le pH est déséquilibré).
2. Nettoyer le filtre avant traitement pour repartir sur une filtration efficace.
3. Verser le floculant liquide directement devant les buses de refoulement, filtration en marche, ou utiliser des cartouches/galets de floculant dans le skimmer selon le produit.
4. Laisser agir avec une filtration continue de plusieurs heures : les particules en suspension s''agglomèrent en flocons.
5. Pour un filtre à sable : baisser le débit ou passer en position "Recirculation" quelques minutes pour laisser les flocons se déposer, puis repasser en "Filtration" en douceur (éviter le backwash qui renvoie tout au fond).
6. Aspirer manuellement à l''évacuation (hors filtre) les dépôts qui se sont déposés au fond.
7. Nettoyer le filtre une fois l''eau limpide.', 'eau trouble, floculation, laiteuse, clarification');
INSERT INTO procedures (id, owner_id, created_by, type, title, category, summary, content, tags) VALUES (16, 1, 2, 'procedure', 'Traiter les algues moutarde (jaunes)', 'Traitement de l''eau', 'Algues jaunâtres résistantes au chlore classique, souvent dans les zones ombragées.', '1. Identifier : dépôt jaunâtre, poudreux, qui se redépose vite après brossage, souvent dans les zones ombragées et les paniers de skimmer.
2. Brosser énergiquement toutes les surfaces touchées et les accessoires (échelle, jouets, maillots à laver aussi car elles s''y accrochent).
3. Réaliser un traitement choc avec un produit anti-algues moutarde spécifique en complément du chlore choc.
4. Nettoyer soigneusement le filtre pendant le traitement (elles s''y logent).
5. Filtration continue 24 à 48h, recontrôler et répéter le brossage/choc si nécessaire.', 'algues moutarde, algues jaunes, traitement');
INSERT INTO procedures (id, owner_id, created_by, type, title, category, summary, content, tags) VALUES (17, 1, 1, 'procedure', 'Traiter les algues noires', 'Traitement de l''eau', 'Les plus résistantes, incrustées dans les joints et micro-fissures.', '1. Identifier : taches noires/bleu-vert incrustées, résistantes au brossage simple, souvent sur joints de carrelage ou liner abîmé.
2. Brosser vigoureusement avec une brosse adaptée au revêtement (brosse inox pour béton/carrelage uniquement, jamais sur liner) pour casser la membrane protectrice de l''algue.
3. Appliquer un traitement anti-algues noires concentré directement sur les taches (produit à action choc localisée).
4. Compléter par un traitement choc chlore de l''ensemble du bassin.
5. Filtration continue, renouveler l''opération après quelques jours si les taches persistent.', 'algues noires, traitement résistant, joints');
INSERT INTO procedures (id, owner_id, created_by, type, title, category, summary, content, tags) VALUES (18, 1, 2, 'procedure', 'Ajuster le TAC (alcalinité)', 'Traitement de l''eau', 'Toujours le premier paramètre à corriger, avant le pH.', '1. Mesurer le TAC (cible 80-120 mg/L / 8-12 °f) avant toute autre correction : c''est toujours le premier paramètre à régler.
2. Si le TAC est trop bas : ajouter un rehausseur de TAC (bicarbonate de sodium), filtration en marche, en une ou plusieurs fois selon la dose totale à apporter.
3. Si le TAC est trop haut : ajouter un réducteur de TAC (acide) par petites doses successives, en laissant agir et recirculer entre chaque ajout.
4. Attendre plusieurs heures (idéalement 24h) filtration en marche avant de recontrôler.
5. Une fois le TAC stabilisé, passer au réglage du pH.', 'TAC, alcalinité, rehausseur, réducteur');
INSERT INTO procedures (id, owner_id, created_by, type, title, category, summary, content, tags) VALUES (19, 1, 1, 'procedure', 'Ajuster le pH (hausse et baisse)', 'Traitement de l''eau', 'À régler après le TAC, en plusieurs petits ajouts.', '1. Mesurer le pH (cible 7.2-7.4) après avoir réglé le TAC.
2. Pour baisser le pH : verser le pH- (liquide ou poudre) directement dans le bassin, filtration en marche, en respectant la dose indiquée sur l''emballage pour le volume du bassin.
3. Pour augmenter le pH : verser le pH+ de la même façon.
4. Ne jamais mélanger pH- et pH+ dans le même traitement, et ne jamais verser un produit concentré directement sur le revêtement ou dans le skimmer.
5. Attendre au moins 2 à 4h, filtration en marche, avant de recontrôler et ajuster à nouveau si besoin.
6. Répartir en plusieurs petits ajouts plutôt qu''une grosse dose unique pour éviter les à-coups.', 'pH, pH plus, pH moins, équilibre eau');
INSERT INTO procedures (id, owner_id, created_by, type, title, category, summary, content, tags) VALUES (20, 1, 2, 'procedure', 'Pompe bruyante ou qui chauffe anormalement', 'Dépannage matériel', 'Diagnostic des causes courantes de bruit et surchauffe moteur.', '1. Couper l''alimentation avant toute intervention.
2. Vérifier une prise d''air (bruit de "gargouillis") : contrôler joint de préfiltre, niveau d''eau, vannes d''aspiration.
3. Vérifier qu''aucun corps étranger n''est coincé dans la turbine (démontage du corps de pompe si besoin).
4. Contrôler que la pompe n''est pas désamorcée ou qu''elle ne fonctionne pas à sec.
5. Vérifier l''état des roulements moteur (bruit métallique aigu = roulements à changer, intervention SAV).
6. Vérifier la ventilation du local technique : un moteur qui chauffe dans un local mal ventilé disjoncte par sécurité thermique.
7. Contrôler la tension d''alimentation et l''état du condensateur si moteur monophasé qui peine à démarrer.', 'pompe, bruit, surchauffe, dépannage, roulements');
INSERT INTO procedures (id, owner_id, created_by, type, title, category, summary, content, tags) VALUES (21, 1, 1, 'procedure', 'Perte de pression ou débit insuffisant malgré filtration', 'Dépannage matériel', 'Méthode de diagnostic étape par étape.', '1. Vérifier le panier du préfiltre pompe et celui des skimmers : un colmatage réduit fortement le débit.
2. Contrôler la pression au manomètre : si elle est haute, le filtre est encrassé (backwash/nettoyage nécessaire) ; si elle est basse, le souci est en amont du filtre.
3. Vérifier les vannes (position, ouverture complète) et l''absence de vanne partiellement fermée par erreur.
4. Rechercher un colmatage dans les canalisations (feuilles, racines sur réseau enterré ancien).
5. Vérifier que la pompe est bien dimensionnée par rapport au filtre et au volume du bassin.
6. Contrôler l''état de la turbine (usure, entartrage) si le débit reste faible après élimination des autres causes.', 'débit, pression, colmatage, dépannage');
INSERT INTO procedures (id, owner_id, created_by, type, title, category, summary, content, tags) VALUES (22, 1, 2, 'procedure', 'Étalonner une sonde de régulation pH/redox', 'Dépannage matériel', 'Étalonnage recommandé tous les 1 à 3 mois pour une régulation fiable.', '1. Couper ou mettre en pause la régulation automatique (pH, chlore/redox) avant l''étalonnage.
2. Démonter la sonde et la rincer à l''eau claire.
3. Tremper la sonde dans une solution étalon pH 7, attendre la stabilisation de la mesure, ajuster si l''appareil le permet (bouton "cal").
4. Rincer puis tremper dans une solution étalon pH 4 (ou 10 selon la plage utilisée), ajuster la pente.
5. Pour une sonde redox : utiliser une solution étalon redox dédiée (souvent 465 mV) et ajuster de la même façon.
6. Rincer, remonter la sonde, relancer la régulation et vérifier la cohérence avec une mesure manuelle (test kit ou photomètre).', 'sonde, régulation, redox, pH, étalonnage');
INSERT INTO procedures (id, owner_id, created_by, type, title, category, summary, content, tags) VALUES (23, 1, 1, 'procedure', 'Pompe à chaleur qui ne chauffe plus ou disjoncte', 'Dépannage matériel', 'Points de contrôle avant intervention d''un frigoriste agréé.', '1. Vérifier que la filtration est bien en marche : une PAC ne chauffe que lorsque l''eau circule (contact de débit).
2. Contrôler la température de consigne et le mode (chauffage/éco) sur le panneau de commande.
3. Vérifier qu''aucun code défaut n''est affiché ; noter le code pour diagnostic ou SAV.
4. Contrôler que l''unité extérieure n''est pas obstruée (feuilles, végétation) et que l''air circule librement autour de l''évaporateur.
5. Vérifier le dégivrage : en dessous de 10-12°C d''air extérieur, un cycle de dégivrage périodique est normal.
6. Si la PAC disjoncte : couper, vérifier l''absence d''humidité dans le boîtier électrique, contrôler le différentiel dédié ; ne pas forcer une remise sous tension répétée, faire intervenir un frigoriste agréé si le défaut persiste.
7. Vérifier le dimensionnement : une PAC sous-dimensionnée peine à maintenir la température par temps frais, ce n''est pas toujours une panne.', 'pompe à chaleur, PAC, chauffage, dépannage, disjoncte');
INSERT INTO procedures (id, owner_id, created_by, type, title, category, summary, content, tags) VALUES (24, 1, 2, 'procedure', 'Détecter une fuite sur le circuit hydraulique', 'Dépannage matériel', 'Méthode du test du seau et recherche de fuite.', '1. Constater une baisse anormale du niveau d''eau (plus de 2 à 3 cm/jour hors évaporation naturelle) : suspecter une fuite.
2. Faire le test du seau (bucket test) : comparer la baisse de niveau du bassin à celle d''un seau rempli posé sur une marche, filtration coupée, sur 24h.
3. Si la fuite persiste filtration coupée : elle est sur la structure du bassin (liner, coque, joints de pièces à sceller).
4. Si la fuite n''apparaît qu''en filtration : elle est sur le circuit hydraulique (canalisations, vannes, joints de pompe/filtre).
5. Inspecter visuellement le local technique et les raccords apparents à la recherche de traces d''humidité.
6. Pour une recherche plus poussée : test à la fumée, colorant traceur sur les points suspects (pièces à sceller, skimmer), ou intervention d''un spécialiste avec électro-détection.
7. Réparer localement (joint, collage, résine étanche) ou faire appel à un professionnel pour une fuite structurelle.', 'fuite, test du seau, niveau d''eau, dépannage');
INSERT INTO procedures (id, owner_id, created_by, type, title, category, summary, content, tags) VALUES (25, 1, 1, 'procedure', 'Remplacer une ampoule ou un spot LED étanche', 'Dépannage matériel', 'Intervention sur un projecteur de piscine, hors tension impérative.', '1. Couper impérativement l''alimentation électrique du projecteur au disjoncteur dédié (jamais d''intervention sous tension en milieu humide).
2. Baisser le niveau d''eau sous le niveau du projecteur si celui-ci doit être sorti de sa niche.
3. Dévisser la vis de sécurité (souvent imperdable) et sortir délicatement le hublot sans tirer sur le câble.
4. Remplacer l''ampoule/le bloc LED par un modèle strictement identique (culot, puissance, tension : 12V pour la plupart des piscines privées).
5. Vérifier et remplacer le joint torique d''étanchéité du hublot avant remontage (graisse silicone légère).
6. Revisser en croix pour une pression homogène, remettre l''eau à niveau, puis remettre sous tension et tester.', 'projecteur, spot, LED, éclairage, dépannage');
INSERT INTO procedures (id, owner_id, created_by, type, title, category, summary, content, tags) VALUES (26, 3, 3, 'procedure', 'Vérifier les dispositifs de sécurité obligatoires', 'Sécurité', 'Contrôle périodique des équipements normalisés (barrière, alarme, couverture, abri).', '1. Identifier le(s) dispositif(s) normalisé(s) installé(s) sur le bassin (barrière NF P90-306, alarme NF P90-307, couverture NF P90-308 ou abri NF P90-309).
2. Barrière : vérifier la hauteur (≥1,10 m), l''absence de prise d''escalade, et surtout le bon fonctionnement du portillon à fermeture et verrouillage automatiques.
3. Alarme : tester le déclenchement (immersion ou périmétrique) et vérifier l''état des piles ; s''assurer qu''elle est réarmée après chaque baignade.
4. Couverture de sécurité : vérifier la tension, l''état des sangles/ancrages, l''absence de déchirure, et sa capacité à supporter le poids d''un enfant.
5. Abri : vérifier le bon coulissement et le verrouillage effectif de la fermeture.
6. Rappeler au client qu''aucun dispositif ne remplace la surveillance active d''un adulte.
7. Consigner la vérification dans la fiche piscine (date, dispositif, état constaté).', 'sécurité, norme NF P90, barrière, alarme, couverture, abri');
INSERT INTO procedures (id, owner_id, created_by, type, title, category, summary, content, tags) VALUES (27, 3, 4, 'procedure', 'Mise en eau d''une piscine neuve', 'Mise en service', 'Premier remplissage et équilibrage d''un bassin neuf.', '1. Vérifier que le bassin est propre (aucun débris de chantier) avant le premier remplissage.
2. Remplir progressivement en surveillant la stabilité de la structure (coque/liner) en respectant les préconisations du poseur.
3. Une fois remplie, mettre en route la filtration en continu pendant 24 à 48h pour homogénéiser l''eau.
4. Réaliser une analyse complète (pH, TAC, TH, chlore, stabilisant) : l''eau de remplissage est rarement équilibrée d''origine.
5. Corriger dans l''ordre : TAC, puis pH, puis TH si besoin.
6. Mettre en route le traitement choisi (chlore, sel...) et laisser le système se stabiliser plusieurs jours avant de considérer l''eau baignable en continu.
7. Ne pas se baigner avant validation des paramètres et respect des délais de sécurité après un traitement choc.', 'mise en eau, piscine neuve, premier remplissage');
INSERT INTO procedures (id, owner_id, created_by, type, title, category, summary, content, tags) VALUES (28, 3, 3, 'procedure', 'Entretien et désinfection d''un spa ou bain à remous', 'Nettoyage', 'Entretien renforcé du fait du faible volume et de la température élevée.', '1. Couper la filtration/chauffage avant intervention.
2. Nettoyer le filtre (cartouche le plus souvent) selon la fréquence préconisée, plus rapprochée que pour une piscine.
3. Contrôler et ajuster pH, TAC et désinfectant (chlore ou brome, souvent privilégié pour les eaux chaudes) à chaque intervention.
4. Vérifier la température (30-40°C typiquement) : cette plage favorise la prolifération de légionelles si l''entretien est négligé.
5. Réaliser une vidange complète et un nettoyage des canalisations avec un produit dégraissant spécial spa tous les 3 à 4 mois.
6. Nettoyer la ligne d''eau et les buses de massage à la brosse douce.
7. Remplir, réajuster les paramètres et relancer avant remise en service.', 'spa, bain à remous, désinfection, légionellose, entretien');
INSERT INTO procedures (id, owner_id, created_by, type, title, category, summary, content, tags) VALUES (53, 1, 1, 'procedure', 'Tester le pH et le chlore avec un kit à pastilles (DPD)', 'Analyse & routine', 'La méthode de référence sur le terrain : Phenol Red pour le pH, DPD1 pour le chlore libre.', '1. Rincer l''éprouvette du testeur avec l''eau du bassin avant le prélèvement.
2. Prélever l''eau à environ 30-40 cm de profondeur, loin des buses de refoulement et des skimmers, pour un échantillon représentatif.
3. Remplir les deux cupules du comparateur jusqu''au repère indiqué.
4. Déposer une pastille Phenol Red dans la cupule pH, une pastille DPD1 dans la cupule chlore.
5. Refermer, agiter légèrement jusqu''à dissolution complète des pastilles.
6. Comparer immédiatement les couleurs obtenues à l''échelle colorimétrique du testeur, à la lumière du jour (jamais en plein soleil direct ni à l''ombre trop sombre).
7. Noter les valeurs et les comparer aux cibles (pH 7.2-7.4, chlore libre 1-3 mg/L).
8. Rincer immédiatement le testeur à l''eau claire après lecture pour éviter toute contamination du test suivant.', 'DPD, phenol red, pastilles, test pH chlore, comparateur');
INSERT INTO procedures (id, owner_id, created_by, type, title, category, summary, content, tags) VALUES (54, 1, 2, 'procedure', 'Tester l''eau avec un photomètre électronique', 'Analyse & routine', 'Outil professionnel pour une lecture précise et multi-paramètres.', '1. Vérifier que la cuve de mesure est propre et sèche, sans rayure sur les faces optiques.
2. Réaliser un "blanc" avec de l''eau du bassin seule (sans réactif) pour calibrer l''appareil sur cet échantillon avant chaque série de mesures.
3. Ajouter le réactif adapté au paramètre recherché (DPD1 pour chlore libre, DPD3 pour chlore total, phénol red pour pH, etc.).
4. Refermer, agiter doucement pour dissoudre sans faire mousser (la mousse fausse la lecture optique).
5. Essuyer l''extérieur de la cuve avant de l''insérer dans l''appareil.
6. Lancer la mesure et lire directement la valeur numérique affichée (généralement en mg/L ou ppm).
7. Nettoyer systématiquement la cuve après chaque test et étalonner l''appareil selon la périodicité du fabricant.
8. Le photomètre permet en général de mesurer en série pH, chlore libre/total, TAC, TH, stabilisant, sel, avec une précision bien supérieure aux bandelettes.', 'photomètre, mesure électronique, précision, étalonnage, chlore libre total');
INSERT INTO procedures (id, owner_id, created_by, type, title, category, summary, content, tags) VALUES (55, 1, 1, 'procedure', 'Effectuer une tournée d''entretien hebdomadaire type', 'Analyse & routine', 'L''ordre d''intervention standard d''un professionnel sur un bassin, en moins de 30 minutes.', '1. Contrôle visuel général en arrivant : couleur de l''eau, niveau, propreté de la plage, état de la couverture/alarme.
2. Vérifier et ajuster le niveau d''eau (idéalement à mi-hauteur des skimmers).
3. Vider et rincer les paniers de skimmer et le préfiltre de la pompe.
4. Brosser les parois, le fond et la ligne d''eau si nécessaire.
5. Passer l''épuisette de surface ou lancer le robot électrique.
6. Contrôler la pression au filtre, faire un backwash si besoin.
7. Tester pH et chlore (et TAC une fois par mois), ajuster les produits en conséquence.
8. Vérifier le bon fonctionnement des équipements (pompe, PAC, électrolyseur, éclairage).
9. Consigner l''intervention (relevés, produits ajoutés, anomalies constatées) dans le carnet de suivi ou l''application.', 'routine, checklist, visite hebdomadaire, tournée');
INSERT INTO procedures (id, owner_id, created_by, type, title, category, summary, content, tags) VALUES (56, 1, 2, 'procedure', 'Entretenir une piscine hors-sol, tubulaire ou autoportée', 'Nettoyage', 'Spécificités liées à la structure légère et au volume réduit.', '1. Vérifier régulièrement la tension de la structure (tubulaire) ou le gonflage (autoportée) : une structure détendue accélère l''usure du liner.
2. Nettoyer plus fréquemment qu''un bassin enterré : le faible volume d''eau se déséquilibre et se réchauffe plus vite, favorisant algues et bactéries.
3. Utiliser une épuisette et un balai manuel adaptés à la taille réduite du bassin plutôt qu''un robot surdimensionné.
4. Contrôler pH et chlore au minimum 2 fois par semaine en pleine saison (contre 1 fois pour un bassin enterré plus stable).
5. Couvrir le bassin hors utilisation pour limiter l''évaporation, les salissures et le réchauffement excessif de l''eau.
6. En fin de saison, vidanger complètement, nettoyer et sécher avant pliage/stockage pour éviter moisissures et détérioration du PVC.
7. Ne jamais laisser un hors-sol totalement vide en plein soleil longtemps : le PVC peut se déformer.', 'hors-sol, tubulaire, autoportée, gonflable, entretien spécifique');
INSERT INTO procedures (id, owner_id, created_by, type, title, category, summary, content, tags) VALUES (57, 1, 1, 'procedure', 'Nettoyer et entretenir un robot électrique', 'Nettoyage', 'Entretien du robot lui-même, en complément du nettoyage du bassin.', '1. Après chaque cycle, sortir le robot de l''eau et le laisser égoutter quelques minutes avant de l''ouvrir.
2. Retirer et rincer le(s) filtre(s)/panier(s) de récupération des déchets à chaque utilisation.
3. Inspecter et nettoyer les brosses : remplacer les brosses mousse après une saison, les brosses PVC après deux saisons environ.
4. Vérifier l''hélice/turbine 1 à 2 fois par saison (davantage en cas d''usage intensif estival) et retirer les débris coincés.
5. Dérouler uniquement la longueur de câble nécessaire au bassin et le stocker toujours bien enroulé, sans le nouer.
6. Stocker le robot au sec, à l''abri du gel et du soleil direct, si possible sur un chariot de transport dédié.
7. Ne jamais faire fonctionner le robot hors de l''eau : cela endommage le moteur.', 'robot électrique, entretien robot, filtre robot, brosses');
INSERT INTO procedures (id, owner_id, created_by, type, title, category, summary, content, tags) VALUES (58, 1, 2, 'procedure', 'Entretenir un robot hydraulique', 'Nettoyage', 'Moins de pannes électroniques, mais un circuit de filtration à surveiller de près.', '1. Vérifier le raccordement à la prise balai ou au skimmer : un joint usé réduit fortement l''aspiration.
2. Contrôler que le sac ou le filtre du robot (selon modèle) n''est pas colmaté, sinon la puissance d''aspiration chute.
3. Nettoyer plus fréquemment le préfiltre de la pompe et le filtre principal : un robot hydraulique sollicite davantage le système de filtration qu''un robot électrique autonome.
4. Vérifier l''absence de plis ou de vrilles sur le tuyau flottant, qui gênent le déplacement aléatoire du robot.
5. Contrôler l''état des membranes/soupapes internes (selon technologie), pièces d''usure à remplacer périodiquement.
6. Ranger le robot et son tuyau à l''ombre hors saison pour limiter le vieillissement du plastique et du caoutchouc.', 'robot hydraulique, prise balai, entretien robot, filtration');
INSERT INTO procedures (id, owner_id, created_by, type, title, category, summary, content, tags) VALUES (59, 1, 1, 'procedure', 'Traiter une eau brune ou tachée (fer, cuivre, manganèse)', 'Traitement de l''eau', 'Identifier la cause avant de traiter, sous peine d''aggraver les taches.', '1. Identifier la teinte : eau verte translucide (cuivre, souvent lié à la corrosion de canalisations ou d''une cellule d''électrolyse), teinte rouille/brune (fer), nuances noires (manganèse).
2. Ramener le pH entre 7.0 et 7.4 avant tout traitement : l''efficacité du séquestrant en dépend directement.
3. Ne pas faire de choc chlore avant d''avoir traité les métaux : un choc sur une eau chargée en métaux précipite et fixe les taches sur les parois.
4. Ajouter un séquestrant métaux (produit "anti-métaux" complexant) selon le dosage indiqué pour le volume du bassin.
5. Laisser agir avec la filtration en marche, sans choc chlore pendant ce délai.
6. Une fois l''eau limpide, reprendre un traitement chlore normal, et renouveler le séquestrant à chaque appoint d''eau important si l''eau du réseau est chargée en métaux.
7. En prévention sur une eau connue pour être chargée en fer/cuivre : ajouter systématiquement le séquestrant à chaque remplissage.', 'eau brune, fer, cuivre, manganèse, séquestrant métaux');
INSERT INTO procedures (id, owner_id, created_by, type, title, category, summary, content, tags) VALUES (60, 1, 2, 'procedure', 'Nettoyer des margelles en pierre naturelle', 'Nettoyage', 'Un entretien doux, sans acide ni haute pression, pour ne pas endommager la pierre.', '1. Balayer ou aspirer les margelles pour retirer les débris avant lavage.
2. Préparer un mélange d''eau tiède et de savon noir (ou liquide vaisselle doux).
3. Frotter avec une brosse à poils souples, jamais de brosse métallique qui raye la pierre.
4. Pour les taches tenaces, appliquer une pâte de bicarbonate de soude directement sur la tache, laisser agir puis frotter.
5. Rincer abondamment à l''eau claire et sécher avec un chiffon propre pour éviter les traces de calcaire.
6. Ne jamais utiliser de nettoyeur haute pression ni de produit acide sur une pierre naturelle : ils attaquent la surface et le jointoiement.
7. Appliquer un traitement hydrofuge/anti-tache une à deux fois par an pour protéger durablement la pierre.', 'margelles, pierre naturelle, nettoyage, hydrofuge');
INSERT INTO procedures (id, owner_id, created_by, type, title, category, summary, content, tags) VALUES (61, 3, 3, 'procedure', 'Réaliser une vidange de piscine dans les règles', 'Mise en service', 'Une vidange mal préparée peut polluer le milieu naturel et endommager le bassin.', '1. Arrêter tout traitement au chlore au moins 15 jours avant la vidange pour laisser le temps au chlore de se neutraliser naturellement.
2. Vérifier auprès de la commune/du service d''assainissement si un rejet au réseau d''eaux usées est autorisé (dérogation possible selon la capacité des ouvrages) ; à défaut, prévoir une infiltration dans le sol via un puits de décantation.
3. Ne jamais rejeter l''eau de vidange directement dans un cours d''eau, un fossé ou le réseau d''eaux pluviales sans neutralisation préalable du chlore.
4. Vidanger progressivement pour un bassin béton/carrelage (risque de soulèvement de la structure en terrain humide si vidé trop vite) ; pour un liner, éviter de laisser le bassin vide trop longtemps (rétractation).
5. Profiter de la vidange pour inspecter et nettoyer en profondeur le fond, les parois et les pièces à sceller.
6. Reremplir et rééquilibrer l''eau selon la procédure de mise en eau (TAC, pH, puis traitement).', 'vidange, rejet eau, réglementation, neutralisation chlore');
INSERT INTO procedures (id, owner_id, created_by, type, title, category, summary, content, tags) VALUES (62, 3, 4, 'procedure', 'Renseigner le carnet sanitaire d''une piscine collective', 'Sécurité', 'Obligation quotidienne pour tout établissement recevant du public avec piscine.', '1. Relever au minimum une fois par jour (davantage en cas de forte fréquentation) : température de l''eau et de l''air, pH, teneur en désinfectant (chlore libre et combiné, ou brome), transparence de l''eau.
2. Consigner chaque relevé avec l''heure et l''identité de la personne ayant réalisé le contrôle.
3. Noter tout incident (dépassement de paramètre, panne, intervention corrective) et l''action corrective mise en œuvre.
4. Conserver le carnet sanitaire sur site : il doit être présenté à toute demande de l''ARS ou du laboratoire agréé lors des contrôles sanitaires.
5. Vérifier la classification de l''établissement (types A à D selon fréquentation) qui détermine la fréquence des prélèvements réglementaires effectués par un laboratoire agréé.
6. Archiver les résultats d''analyses du laboratoire agréé avec le carnet : ils font partie intégrante du dossier sanitaire de l''établissement.', 'carnet sanitaire, piscine collective, ARS, ERP, traçabilité');
INSERT INTO procedures (id, owner_id, created_by, type, title, category, summary, content, tags) VALUES (63, 1, 1, 'procedure', 'Nettoyer le bac tampon d''une piscine à débordement ou miroir', 'Filtration', 'Le bac tampon concentre toutes les impuretés de surface : un entretien négligé y favorise vite les algues.', '1. Couper la pompe avant intervention si le bac tampon nécessite un accès direct.
2. Ouvrir le regard/trappe d''accès au bac tampon (généralement à proximité du local technique).
3. Retirer manuellement les feuilles, insectes et débris flottants accumulés.
4. Vérifier l''état de la sonde de niveau et de l''électrovanne de régulation (trop-plein/appoint) : les nettoyer si elles sont entartrées ou encrassées.
5. Brosser les parois du bac tampon si un dépôt ou un début d''algue est visible, puis passer un coup d''épuisette fine.
6. Profiter de l''intervention pour contrôler le bon fonctionnement de la pompe de reprise du bac tampon vers la filtration.
7. À prévoir en moyenne une fois par mois en saison, plus souvent en cas de forte présence de végétation aux abords du bassin.', 'bac tampon, débordement, miroir, entretien mensuel');
INSERT INTO procedures (id, owner_id, created_by, type, title, category, summary, content, tags) VALUES (64, 1, 2, 'procedure', 'Réagir en cas de fuite ou d''odeur de chlore gazeux', 'Sécurité', 'Procédure d''urgence à connaître pour toute intervention en local technique.', '1. Ne jamais chercher à identifier ou colmater seul une fuite de chlore gazeux : évacuer immédiatement la zone.
2. Faire sortir toute personne à proximité à l''air libre, de préférence en hauteur (le chlore gazeux est plus lourd que l''air et stagne au sol).
3. Ne pas retourner dans le local avant l''intervention des secours ou d''un professionnel équipé (appareil respiratoire isolant).
4. En cas d''exposition (toux, picotements de gorge, larmoiement, difficultés respiratoires) : évacuer la victime à l''air frais, la mettre au repos, ne pas la faire marcher inutilement.
5. Rincer abondamment les yeux à l''eau tiède en cas de projection, retirer les vêtements contaminés.
6. Appeler les secours (15 ou 112) en cas de symptômes respiratoires ou d''exposition prolongée.
7. Ne jamais utiliser d''eau pour "laver" une fuite de produit chloré solide/granulés à proximité d''un autre produit chimique : risque de réaction violente.', 'chlore gazeux, fuite, urgence, premiers secours, sécurité local technique');
INSERT INTO procedures (id, owner_id, created_by, type, title, category, summary, content, tags) VALUES (29, 1, 1, 'information', 'Valeurs idéales de l''équilibre de l''eau', 'Chimie de l''eau', 'Tableau de référence des paramètres clés à contrôler à chaque analyse.', 'pH : 7.2 à 7.4 (zone où le désinfectant est le plus efficace et l''eau confortable pour la peau/yeux).
Chlore libre : 1,0 à 3,0 mg/L (2 mg/L en usage courant, jusqu''à 3-5 mg/L en traitement choc temporaire).
Chlore combiné (chloramines) : doit rester proche de 0, idéalement inférieur à 0,4 mg/L — un taux élevé signale une eau mal désinfectée malgré un chlore libre correct.
TAC (alcalinité) : 80 à 120 mg/L (8 à 12 °f).
TH (dureté) : 100 à 300 mg/L de CaCO3 selon le revêtement (viser plutôt le bas de la fourchette pour un liner, plus haut pour un béton/carrelage).
Stabilisant (acide cyanurique) : 20 à 50 mg/L pour un traitement au chlore stabilisé ; proche de 0 pour un traitement non stabilisé (sel, oxygène actif).
Température : 26 à 28°C pour un confort de baignade classique, au-delà de 28°C la vigilance sur le traitement doit augmenter.', 'valeurs idéales, pH, chlore, TAC, TH, stabilisant, référence');
INSERT INTO procedures (id, owner_id, created_by, type, title, category, summary, content, tags) VALUES (30, 1, 1, 'information', 'Chlore libre, combiné et total : bien comprendre les chloramines', 'Chimie de l''eau', 'Le chlore combiné ne désinfecte plus et sent fort : c''est un signe de sous-chloration.', 'Le chlore libre est la fraction active du chlore, celle qui désinfecte réellement l''eau. Le chlore combiné (chloramines) résulte de la réaction du chlore avec les matières organiques apportées par les baigneurs (sueur, urée, crèmes solaires) : il ne désinfecte plus et c''est lui qui est responsable de l''odeur de "chlore" typique et des irritations des yeux — une eau qui sent fort le chlore est en réalité souvent sous-chlorée.
Le chlore total = chlore libre + chlore combiné. Un chlore combiné supérieur à 0,4-0,6 mg/L impose un traitement choc pour "casser" les chloramines et retrouver du chlore libre actif.', 'chlore, chloramines, chlore combiné, odeur chlore');
INSERT INTO procedures (id, owner_id, created_by, type, title, category, summary, content, tags) VALUES (31, 1, 1, 'information', 'Le TAC et son rôle de tampon du pH', 'Chimie de l''eau', 'Pourquoi le TAC doit toujours être réglé avant le pH.', 'Le TAC (Titre Alcalimétrique Complet) mesure la capacité de l''eau à résister aux variations de pH : c''est l''effet "tampon". Un TAC trop bas rend le pH instable (il varie fortement au moindre ajout de produit ou apport extérieur), tandis qu''un TAC trop élevé rend le pH difficile à corriger et favorise l''entartrage.
C''est pourquoi le TAC doit toujours être réglé en premier, avant le pH : régler le pH sur un TAC déséquilibré est inefficace, le pH "revient" rapidement à sa valeur d''origine.', 'TAC, alcalinité, tampon, pH stable');
INSERT INTO procedures (id, owner_id, created_by, type, title, category, summary, content, tags) VALUES (32, 1, 1, 'information', 'Le stabilisant (acide cyanurique) : rôle et risque de sur-stabilisation', 'Chimie de l''eau', 'Le stabilisant protège le chlore des UV mais ne se dégrade jamais naturellement.', 'Le stabilisant protège le chlore des UV du soleil, qui le détruisent sinon en 2 à 3h en plein été. Il est indispensable pour une piscine extérieure traitée au chlore.
Mais il présente un piège : il s''accumule dans l''eau au fil des ajouts de chlore stabilisé et ne se dégrade pas naturellement — seule une dilution (renouvellement d''eau) le fait baisser. Au-delà de 50 mg/L, on parle de sur-stabilisation : le chlore devient de moins en moins efficace à dose égale ("effet de verrouillage"), ce qui pousse à sur-doser, aggravant le problème.
Solution : renouveler une partie de l''eau du bassin, ou passer temporairement à un chlore non stabilisé.', 'stabilisant, acide cyanurique, sur-stabilisation, verrouillage chlore');
INSERT INTO procedures (id, owner_id, created_by, type, title, category, summary, content, tags) VALUES (33, 1, 2, 'information', 'L''indice de Langelier et l''équilibre calco-carbonique', 'Chimie de l''eau', 'Détermine si une eau est entartrante, corrosive, ou équilibrée.', 'L''indice de Langelier (LSI) synthétise pH, TAC, TH et température pour déterminer si une eau est entartrante, corrosive, ou équilibrée. Un résultat proche de 0 (± 0,3) signale une eau à l''équilibre : c''est l''objectif à viser.
Un indice positif indique une eau entartrante (dépôts de calcaire sur parois, canalisations, cellule d''électrolyse). Un indice négatif indique une eau corrosive/agressive (attaque des joints, du revêtement, des pièces métalliques).
Une eau durablement déséquilibrée abîme aussi bien le bassin que les équipements de filtration et de traitement — l''équilibre calco-carbonique doit donc être surveillé au même titre que la désinfection.', 'Langelier, équilibre calco-carbonique, entartrage, corrosion');
INSERT INTO procedures (id, owner_id, created_by, type, title, category, summary, content, tags) VALUES (34, 1, 1, 'information', 'Ordre de correction des paramètres de l''eau', 'Chimie de l''eau', 'La méthode professionnelle : TAC, puis pH, puis TH, puis chlore.', 'Lorsque plusieurs paramètres sont à corriger en même temps, respecter systématiquement cet ordre :
1) TAC (alcalinité) — il stabilise le pH et doit être réglé en premier.
2) pH — une fois le TAC dans la cible.
3) TH (dureté) si nécessaire.
4) Chlore et stabilisant en dernier, une fois pH/TAC stabilisés (le chlore est plus efficace et plus facile à ajuster sur une eau déjà équilibrée).
Attendre systématiquement quelques heures filtration en marche entre chaque correction avant de recontrôler.', 'ordre correction, TAC pH TH, méthode');
INSERT INTO procedures (id, owner_id, created_by, type, title, category, summary, content, tags) VALUES (35, 1, 1, 'information', 'Chlore stabilisé vs non stabilisé : lequel utiliser', 'Chimie de l''eau', 'Stabilisé pour le traitement continu, non stabilisé pour le rattrapage.', 'Le chlore stabilisé (galets, pastilles, dichlore) contient de l''acide cyanurique qui protège le chlore des UV : c''est la solution adaptée à la désinfection continue d''une piscine extérieure.
Le chlore non stabilisé (hypochlorite de calcium en poudre/granulés) agit vite et ne contient pas de stabilisant : il est réservé au traitement choc ponctuel, notamment pour rattraper une eau verte, sans faire grimper davantage le taux de stabilisant déjà présent.
Une piscine déjà sur-stabilisée doit systématiquement être traitée avec du chlore non stabilisé jusqu''à dilution du stabilisant en excès.', 'chlore stabilisé, chlore non stabilisé, dichlore, hypochlorite de calcium');
INSERT INTO procedures (id, owner_id, created_by, type, title, category, summary, content, tags) VALUES (36, 1, 2, 'information', 'Les différents systèmes de traitement de l''eau', 'Équipements', 'Chlore, brome, sel, oxygène actif, PHMB, UV, ozone : avantages et inconvénients.', 'Chlore (galets/liquide) : référence historique, efficace et économique, nécessite une gestion régulière du stabilisant.
Brome : mieux toléré par les peaux sensibles, plus stable en eau chaude (adapté aux spas), mais plus coûteux.
Sel/électrolyse : production de chlore in situ par une cellule, confort de baignade apprécié, nécessite un contrôle régulier du taux de sel (généralement 3 à 5 g/L) et un détartrage périodique de la cellule.
Oxygène actif : sans odeur, doux pour la peau, adapté aux petits bassins/spas familiaux, mais moins rémanent et plus cher à l''usage.
PHMB (polymère) : sans chlore, incompatible avec un passage ultérieur au chlore sans vidange complète.
UV et ozone : traitements complémentaires (pas des désinfectants rémanents à eux seuls) qui réduisent la consommation de désinfectant chimique.', 'chlore, brome, sel, électrolyse, oxygène actif, PHMB, UV, ozone');
INSERT INTO procedures (id, owner_id, created_by, type, title, category, summary, content, tags) VALUES (37, 1, 1, 'information', 'Reconnaître les différents types d''algues', 'Algues & pathologies de l''eau', 'Vertes, moutarde, noires, roses : identification rapide.', 'Algues vertes : les plus courantes, eau uniformément verte et/ou parois glissantes, liées à un manque de désinfectant ou un déséquilibre du pH.
Algues moutarde (jaunes) : aspect poudreux jaunâtre, se redéposent vite après brossage, résistantes au chlore classique, nécessitent un produit spécifique.
Algues noires : taches noires incrustées très résistantes, se logent dans les joints et micro-fissures, demandent un brossage mécanique pour casser leur membrane avant traitement.
Algues roses : en réalité des bactéries (et non de vraies algues), colonisent surtout les surfaces plastiques (liner, joints, paniers de skimmer), traitement bactéricide spécifique nécessaire en complément du chlore.', 'algues vertes, moutarde, noires, roses, identification');
INSERT INTO procedures (id, owner_id, created_by, type, title, category, summary, content, tags) VALUES (38, 1, 1, 'information', 'Comparatif des systèmes de filtration', 'Équipements', 'Sable, cartouche, diatomées, verre : finesse et entretien.', 'Sable : le plus répandu et économique, finesse de filtration 30-40 microns, entretien par backwash bihebdomadaire/bimensuel, sable à remplacer tous les 5-7 ans.
Cartouche : finesse 15-20 microns, pas de backwash (économie d''eau), nettoyage manuel 1 à 2 fois par semaine en pleine saison, cartouche à remplacer tous les 2-3 ans.
Diatomées : finesse 1-3 microns, eau la plus limpide, entretien plus technique (rechargement périodique en terre de diatomées), recommandé pour un professionnel.
Verre recyclé : alternative au sable, filtration fine, meilleure résistance à l''entartrage, backwash mensuel, durée de vie proche de 8 ans.', 'filtration, sable, cartouche, diatomées, verre, comparatif');
INSERT INTO procedures (id, owner_id, created_by, type, title, category, summary, content, tags) VALUES (39, 1, 2, 'information', 'Comprendre une pompe de filtration', 'Équipements', 'Débit, HMT et dimensionnement.', 'Une pompe de filtration se caractérise par son débit (m³/h) et sa hauteur manométrique totale (HMT, la capacité à "pousser" l''eau en compensant les pertes de charge du circuit).
Le dimensionnement doit permettre de filtrer l''intégralité du volume du bassin dans le temps de filtration quotidien visé, tout en tenant compte des pertes de charge du filtre, des canalisations et des accessoires.
Une pompe surdimensionnée use prématurément le filtre et consomme inutilement ; une pompe sous-dimensionnée ne brasse pas assez l''eau et laisse le traitement moins efficace. Les pompes à vitesse variable permettent d''adapter le débit aux besoins réels avec un gain énergétique important.', 'pompe, débit, HMT, dimensionnement, vitesse variable');
INSERT INTO procedures (id, owner_id, created_by, type, title, category, summary, content, tags) VALUES (40, 1, 1, 'information', 'Comprendre une pompe à chaleur piscine', 'Équipements', 'COP, dimensionnement et plage de fonctionnement.', 'Une pompe à chaleur (PAC) capte les calories de l''air extérieur pour chauffer l''eau du bassin. Sa performance se mesure par le COP (Coefficient de Performance) : un COP de 4 signifie 4 kW de chaleur restitués pour 1 kW électrique consommé.
Le COP varie fortement avec la température extérieure : il chute quand l''air se refroidit, ce qui explique une chauffe moins efficace en intersaison. La Fédération des Professionnels de la Piscine impose deux mesures de référence pour comparer les modèles (air 15°C/eau 26°C, et air 28°C/eau 28°C).
Dimensionnement indicatif : environ 1 kW de puissance pour 10 m³ d''eau, à affiner selon le volume exact, l''exposition, la couverture du bassin et la vitesse de montée en température souhaitée.', 'pompe à chaleur, PAC, COP, chauffage piscine, dimensionnement');
INSERT INTO procedures (id, owner_id, created_by, type, title, category, summary, content, tags) VALUES (41, 1, 1, 'information', 'Durée de filtration recommandée selon la température de l''eau', 'Calculs & formules', 'La règle professionnelle : température divisée par 2.', 'Règle professionnelle simple : durée de filtration (en heures) = température de l''eau (°C) ÷ 2. Exemple : 24°C → 12h de filtration/jour, 28°C → 14h, 30°C → 15h.
En dessous de 12°C, les micro-organismes ne prolifèrent quasiment plus : la filtration peut être fortement réduite. Au-dessus de 28°C, la filtration doit tourner en continu (24h/24) pour éviter qu''une eau chaude ne verdisse en 24 à 48h.
Cette règle reste indicative : l''adapter à la fréquentation du bassin (plus de baigneurs = plus de filtration) et à l''environnement (végétation, exposition au vent).', 'durée filtration, température, règle température divisée par 2');
INSERT INTO procedures (id, owner_id, created_by, type, title, category, summary, content, tags) VALUES (42, 1, 2, 'information', 'Calculer le volume d''un bassin selon sa forme', 'Calculs & formules', 'Formules par forme + conversion en litres.', 'Rectangulaire : Longueur × Largeur × Profondeur moyenne.
Ronde : Rayon × Rayon × 3,14 × Profondeur moyenne.
Ovale : Longueur × Largeur × Profondeur moyenne × 0,89.
Forme libre : décomposer le bassin en formes géométriques simples et additionner les volumes obtenus, ou utiliser l''estimation rapide Longueur max × Largeur max × Profondeur moyenne × 0,85.
Toujours privilégier la profondeur moyenne (et non la profondeur maximale) pour un résultat fiable. Conversion : 1 m³ = 1 000 litres.', 'volume piscine, calcul, formule, m3, litres');
INSERT INTO procedures (id, owner_id, created_by, type, title, category, summary, content, tags) VALUES (43, 1, 1, 'information', 'Calculer le dosage d''un produit selon le volume du bassin', 'Calculs & formules', 'Méthode en 4 étapes pour doser correctement.', 'La quasi-totalité des produits de traitement (pH+/pH-, chlore choc, rehausseur/réducteur de TAC, anti-algues) sont dosés en fonction du volume d''eau du bassin, indiqué sur l''emballage en g ou mL par m³.
Méthode : 1) connaître le volume exact du bassin (voir fiche calcul de volume) ; 2) mesurer l''écart entre la valeur actuelle et la valeur cible du paramètre ; 3) appliquer la dose indiquée par le fabricant pour cet écart et ce volume ; 4) fractionner les doses importantes en plusieurs apports espacés de quelques heures plutôt qu''un apport unique, pour limiter les à-coups et mieux contrôler le résultat.', 'dosage, calcul produit, volume, traitement');
INSERT INTO procedures (id, owner_id, created_by, type, title, category, summary, content, tags) VALUES (44, 3, 3, 'information', 'Réglementation sécurité des piscines privées', 'Réglementation & sécurité', 'Loi du 3 janvier 2003 et normes NF P90-306/307/308/309.', 'Depuis la loi n°2003-9 du 3 janvier 2003, toute piscine enterrée ou semi-enterrée non close à usage individuel ou collectif doit être équipée d''au moins un dispositif de sécurité normalisé, en vue de prévenir les noyades d''enfants de moins de 5 ans.
Quatre normes définissent ces dispositifs : NF P90-306 (barrières de protection, hauteur minimale 1,10 m, portillon à fermeture et verrouillage automatiques), NF P90-307 (alarmes, détection périmétrique ou d''immersion), NF P90-308 (couvertures de sécurité) et NF P90-309 (abris de piscine).
Le non-respect de cette obligation expose le propriétaire à une amende pouvant atteindre 45 000 €. Ces dispositifs réduisent le risque mais ne remplacent jamais la surveillance active d''un adulte.', 'sécurité piscine, loi 2003, NF P90-306, NF P90-307, NF P90-308, NF P90-309');
INSERT INTO procedures (id, owner_id, created_by, type, title, category, summary, content, tags) VALUES (45, 3, 3, 'information', 'Norme électrique des piscines (NF C15-100)', 'Réglementation & sécurité', 'Volumes de protection et règles pour le local technique.', 'La norme NF C15-100 (section 702) encadre les installations électriques à proximité d''un bassin. Elle définit des volumes de protection autour de la piscine (0, 1 et 2) : plus on est proche de l''eau, plus les restrictions sur le matériel électrique autorisé sont sévères.
Le tableau électrique dédié à la piscine doit être séparé de celui de l''habitation et comporter un interrupteur différentiel 30 mA. Pour s''affranchir des contraintes des volumes de protection, le local technique (et donc la pompe en 230V) doit idéalement être installé à plus de 3,50 m du bord du bassin ; la ventilation et l''étanchéité du local sont essentielles.', 'NF C15-100, électricité piscine, volumes de protection, local technique');
INSERT INTO procedures (id, owner_id, created_by, type, title, category, summary, content, tags) VALUES (46, 3, 4, 'information', 'Stockage et manipulation des produits chimiques', 'Réglementation & sécurité', 'Ne jamais mélanger chlore et acide : consignes de sécurité essentielles.', 'Ne jamais stocker le chlore et l''acide côte à côte, ni mélanger différents types de chlore entre eux : le contact accidentel entre chlore et acide peut générer un dégagement de gaz toxique voire une réaction violente.
Conserver chaque produit dans son emballage d''origine, étiqueté, dans un local frais, sec, aéré et à l''abri du soleil direct. Prévoir un espace entre les différents contenants et une bonne ventilation pour éviter toute accumulation de vapeurs.
Stocker hors de portée des enfants et des animaux. Porter des gants et des lunettes de protection lors de toute manipulation de produits concentrés, et toujours verser le produit dans l''eau (jamais l''inverse) lors d''une dilution.', 'sécurité chimique, stockage produits, chlore acide, EPI');
INSERT INTO procedures (id, owner_id, created_by, type, title, category, summary, content, tags) VALUES (47, 3, 3, 'information', 'Risque de légionellose dans les spas et bains à remous', 'Réglementation & sécurité', 'La plage de température des spas est aussi celle de prolifération de la bactérie.', 'La légionellose est une infection pulmonaire grave provoquée par l''inhalation d''aérosols contenant la bactérie Legionella pneumophila. Les spas et bains à remous sont particulièrement à risque : leur température de fonctionnement (30 à 40°C) se situe précisément dans la zone de multiplication optimale de la bactérie (25-45°C, avec un pic entre 32 et 42°C où la population double toutes les 3-4h), combinée à un faible volume d''eau et une forte agitation générant des aérosols.
La prévention passe par un contrôle rigoureux et permanent du désinfectant, une vidange et un nettoyage complet des canalisations réguliers (tous les 3-4 mois), et la lutte contre l''entartrage/la corrosion qui favorisent la formation de biofilm, terrain propice à la bactérie.', 'légionellose, spa, bain à remous, sécurité sanitaire');
INSERT INTO procedures (id, owner_id, created_by, type, title, category, summary, content, tags) VALUES (48, 1, 1, 'information', 'Les différents revêtements de piscine et leur entretien', 'Équipements', 'Liner, PVC armé, coque, béton/carrelage, enduit : spécificités d''entretien.', 'Liner (PVC souple) : économique, confortable, mais sensible aux perforations et à la décoloration ; nettoyage à la brosse douce, jamais de brosse métallique ou de produit abrasif.
PVC armé : plus résistant et étanche que le liner classique, soudé, adapté aux formes complexes, entretien similaire au liner.
Coque polyester : très lisse (peu d''accroche pour les algues), durable, mais réparation délicate en cas de fissure (résine spécifique).
Béton/carrelage : très résistant et personnalisable, mais surface plus poreuse et rugueuse propice à l''accroche des algues (notamment noires dans les joints) ; supporte le brossage avec une brosse plus agressive.
Enduit : intermédiaire, à réimperméabiliser périodiquement, sensible à l''équilibre de l''eau (indice de Langelier à surveiller de près).', 'liner, PVC armé, coque, béton, carrelage, enduit, revêtement');
INSERT INTO procedures (id, owner_id, created_by, type, title, category, summary, content, tags) VALUES (49, 1, 2, 'information', 'Calendrier annuel d''entretien d''une piscine', 'Calendrier & organisation', 'Checklist saisonnière pour organiser sa tournée sur l''année.', 'Printemps (remise en route) : retrait de la bâche, remontage du matériel, nettoyage complet, backwash, remise à niveau des paramètres, choc si besoin.
Été (haute saison) : contrôle des paramètres 1 à 2 fois par semaine, nettoyage skimmers/ligne d''eau hebdomadaire, filtration selon la règle température/2, vigilance accrue lors des orages et fortes chaleurs.
Automne : réduction progressive de la filtration à mesure que la température baisse, nettoyage renforcé (feuilles), dernière analyse complète avant hivernage.
Hiver (hivernage) : mise en hivernage passif ou actif selon la région et le type de bassin, surveillance ponctuelle du niveau d''eau et de l''état de la couverture pendant la période fermée.', 'calendrier, saisons, planning entretien, checklist annuelle');
INSERT INTO procedures (id, owner_id, created_by, type, title, category, summary, content, tags) VALUES (50, 1, 1, 'information', 'Glossaire des termes techniques du métier', 'Glossaire', 'Vocabulaire de base à connaître.', 'Backwash (contre-lavage) : inversion du sens de circulation de l''eau dans un filtre à sable/diatomées pour évacuer les impuretés retenues.
Skimmer : écumoire intégrée à la paroi du bassin qui aspire l''eau de surface.
Bonde de fond : prise d''aspiration au point le plus bas du bassin, soumise à un dispositif anti-vortex/anti-entraînement.
Vanne multivoie : vanne du filtre à sable permettant de sélectionner le mode (filtration, lavage, rinçage, vidange, recirculation, hivernage).
Refoulement : buse qui renvoie l''eau filtrée dans le bassin.
Ligne d''eau : bande à la surface du bassin où se déposent calcaire, graisses et pollens.
HMT : Hauteur Manométrique Totale, capacité d''une pompe à vaincre les pertes de charge du circuit.', 'glossaire, vocabulaire, lexique, termes techniques');
INSERT INTO procedures (id, owner_id, created_by, type, title, category, summary, content, tags) VALUES (51, 3, 3, 'information', 'Premiers secours et prévention de la noyade', 'Réglementation & sécurité', 'La noyade reste la 1ère cause de mort accidentelle chez les moins de 5 ans avec piscine.', 'La noyade reste la première cause de mort accidentelle chez les enfants de moins de 5 ans en France disposant d''une piscine privée.
Rappels essentiels à transmettre systématiquement aux clients : surveillance active et continue d''un adulte dès qu''un enfant est à proximité de l''eau, même équipée d''un dispositif de sécurité normalisé (aucun dispositif n''est infaillible ni ne dispense de surveillance) ; ne jamais laisser un enfant seul même quelques instants ; réarmer systématiquement alarme/couverture après chaque utilisation.
En cas de noyade : sortir la victime de l''eau, alerter les secours (15 ou 112), débuter une réanimation cardio-pulmonaire (RCP) si la victime ne respire pas — la formation aux gestes qui sauvent (PSC1) est vivement recommandée pour tout professionnel intervenant sur des piscines.', 'noyade, premiers secours, RCP, prévention, sécurité enfants');
INSERT INTO procedures (id, owner_id, created_by, type, title, category, summary, content, tags) VALUES (52, 1, 1, 'information', 'Fiches produits : rôle et précautions des principaux produits de traitement', 'Chimie de l''eau', 'Chlore choc, galets, pH+/pH-, floculant, séquestrant.', 'Chlore choc (dichlore/hypochlorite) : désinfection rapide et rattrapage, à diluer avant usage pour la poudre, jamais en contact direct avec la peau.
Galets de chlore lent (trichlore stabilisé) : diffusion progressive sur 7-10 jours en skimmer ou diffuseur flottant, jamais dans le panier du skimmer si filtration coupée (concentration dangereuse localisée).
pH+/pH- : produits acido-basiques concentrés, toujours verser dans l''eau et non l''inverse, stocker séparément l''un de l''autre.
Anti-algues : à utiliser en traitement préventif régulier ou curatif ciblé selon le type d''algue, vérifier la compatibilité avec le désinfectant utilisé.
Floculant : agent clarifiant à action physique (agglomération des particules), sans effet désinfectant, à utiliser en complément du chlore et non à sa place.
Séquestrant/anti-calcaire : limite la précipitation du calcaire et des métaux responsables de taches et d''eau trouble/colorée, à renouveler régulièrement.', 'produits, chlore choc, galets, pH, floculant, séquestrant, précautions');
INSERT INTO procedures (id, owner_id, created_by, type, title, category, summary, content, tags) VALUES (65, 1, 1, 'information', 'Comparatif des méthodes de test d''eau', 'Chimie de l''eau', 'Bandelettes, gouttes, pastilles DPD, photomètre : précision et usage.', 'Bandelettes réactives : trempette de 5 secondes, lecture après 10-15 secondes par comparaison colorimétrique. Rapides et pratiques pour un contrôle quotidien, mais précision limitée et sensibles à la péremption.
Trousse à gouttes (réactifs liquides) : quelques gouttes de réactif dans une éprouvette d''eau, lecture par comparaison de couleur. Un peu plus précises que les bandelettes, matériel économique.
Pastilles DPD (Phenol Red pour le pH, DPD1 pour le chlore libre, DPD3 pour le chlore total) : méthode de référence des professionnels sur le terrain, bon compromis précision/rapidité.
Photomètre électronique : lecture optique numérique, la plus précise, multi-paramètres (pH, chlore libre/total, TAC, TH, stabilisant, sel...), incontournable pour un usage professionnel régulier ou une piscine collective.
Pour un résultat fiable quelle que soit la méthode : prélever l''échantillon à 30-40 cm de profondeur, loin des points d''injection de produit, et tester rapidement après le prélèvement.', 'méthodes de test, bandelettes, DPD, photomètre, comparatif');
INSERT INTO procedures (id, owner_id, created_by, type, title, category, summary, content, tags) VALUES (66, 1, 2, 'information', 'Fréquence des tests d''eau : piscine privée vs collective', 'Chimie de l''eau', 'Les obligations de contrôle changent radicalement selon le type d''établissement.', 'Piscine privée familiale : contrôle du pH et du chlore recommandé de façon hebdomadaire au minimum en pleine saison, davantage après une forte fréquentation, un orage ou une chaleur intense. Le TAC et le stabilisant se contrôlent plus ponctuellement (mensuel).
Piscine collective (hôtel, camping, résidence, établissement recevant du public) : contrôle interne obligatoire au minimum une fois par jour (température, pH, désinfectant, transparence), consigné dans le carnet sanitaire. À cela s''ajoute un contrôle sanitaire externe par un laboratoire agréé mandaté par l''ARS, à fréquence réglementaire selon la classification de l''établissement (type A à D).
Un professionnel intervenant sur un parc de piscines privées doit adapter sa fréquence de passage à la saison, au volume, à la fréquentation et aux paramètres constatés lors du dernier passage plutôt qu''à un rythme rigide.', 'fréquence test, piscine collective, piscine privée, ARS');
INSERT INTO procedures (id, owner_id, created_by, type, title, category, summary, content, tags) VALUES (67, 1, 1, 'information', 'Erreurs courantes de mesure du pH et du chlore', 'Chimie de l''eau', 'La majorité des résultats aberrants viennent d''une erreur de prélèvement ou de réactif, pas de l''eau elle-même.', 'Réactifs périmés : les réactifs liquides (DPD, phénol red) se conservent environ un an ; passé ce délai, les résultats deviennent peu fiables.
Contamination : toucher l''embout du flacon ou la bandelette avec les doigts, ou mal refermer un bouchon, contamine le réactif et fausse durablement les tests suivants.
Stockage inadapté : conserver les réactifs à l''abri de la lumière et de la chaleur (5 à 22°C) ; un flacon laissé au soleil dans la caisse à outils se dégrade vite.
Mauvais timing de lecture : lire trop tôt ou trop tard après la réaction chimique change la couleur perçue et donc la valeur lue.
pH trop bas ou trop haut faussant la lecture du chlore : en dessous de 7,0 ou au-dessus de 7,8, l''efficacité et la détection du chlore par les réactifs se dégradent — toujours contrôler le pH en même temps que le chlore.
Prélèvement non représentatif : un échantillon pris en surface ou juste après un ajout de produit ne reflète pas l''état réel du bassin.', 'erreurs mesure, réactifs périmés, contamination, fiabilité test');
INSERT INTO procedures (id, owner_id, created_by, type, title, category, summary, content, tags) VALUES (68, 3, 3, 'information', 'Réglementation des piscines collectives (ARS)', 'Réglementation & sécurité', 'Carnet sanitaire, classification des établissements et contrôle sanitaire externe.', 'Toute piscine à usage collectif (hôtel, camping, résidence de tourisme, centre de vacances...) est soumise à une obligation de moyens et de résultats en matière de sécurité sanitaire de l''eau, encadrée notamment par l''arrêté du 26 mai 2021.
Les établissements sont classés en 4 types (A à D) selon leur nature et leur fréquentation, ce qui détermine la fréquence du contrôle sanitaire réalisé par un laboratoire agréé pour le compte de l''ARS (Agence Régionale de Santé) : pour les piscines de type A la fréquence peut descendre jusqu''à une fois tous les deux mois ; les établissements saisonniers (ouverture ≤ 6 mois) doivent être contrôlés au moins 2 fois par période d''ouverture.
En complément du contrôle externe, l''exploitant doit assurer un autocontrôle quotidien (température, pH, désinfectant, transparence) consigné dans le carnet sanitaire, document obligatoire à présenter lors de toute inspection.', 'ARS, piscine collective, carnet sanitaire, classification établissement');
INSERT INTO procedures (id, owner_id, created_by, type, title, category, summary, content, tags) VALUES (69, 1, 1, 'information', 'Différences pratiques : piscine hors-sol, gonflable, tubulaire, enterrée', 'Équipements', 'Le faible volume et la structure légère changent radicalement le rythme d''entretien.', 'Piscine gonflable : installation/désinstallation saisonnière voire ponctuelle, très faible volume, eau souvent simplement renouvelée plutôt que traitée en continu, structure fragile sensible à l''usure.
Piscine tubulaire/autoportée : installation plus durable sur la saison, nécessite une vraie filtration et un suivi régulier de l''eau comme un bassin enterré, mais avec un volume réduit qui se déséquilibre et se réchauffe beaucoup plus vite (contrôles plus fréquents nécessaires).
Piscine enterrée : volume plus important qui offre une meilleure inertie et stabilité des paramètres, mais nécessite des équipements fixes (filtration, éventuellement PAC/électrolyseur) et le nettoyage de tous ses recoins fixes (skimmers, ligne d''eau, margelles).
Dans tous les cas, le principe reste le même (filtration + équilibre de l''eau + désinfection) mais la fréquence et l''intensité des gestes doivent être adaptées au volume et à la stabilité thermique du bassin.', 'hors-sol, gonflable, tubulaire, enterrée, comparatif');
INSERT INTO procedures (id, owner_id, created_by, type, title, category, summary, content, tags) VALUES (70, 1, 2, 'information', 'Piscine à débordement / miroir : fonctionnement du bac tampon', 'Équipements', 'Le bac tampon, spécificité technique de ces bassins, s''entretient comme un skimmer géant.', 'Dans une piscine à débordement, l''eau s''écoule en continu par une ou plusieurs goulottes vers un bac tampon (ou bac de rétention), un réservoir indépendant du bassin qui reçoit toute l''eau de surface avec les déchets qu''elle transporte (feuilles, pollens, résidus de crème solaire...). Ce bac représente généralement environ 10% du volume total du bassin.
Le bac tampon est équipé d''une sonde de niveau et d''une électrovanne d''appoint qui régulent automatiquement le niveau d''eau (compensant l''évaporation et les éclaboussures).
Quand le débordement est total sur tous les côtés du bassin, on parle de piscine "miroir" : l''eau affleure exactement le niveau du sol pour un effet visuel de reflet.
L''entretien du bac tampon (nettoyage régulier des déchets accumulés, contrôle de la sonde et de l''électrovanne) est indispensable : négligé, il devient un foyer de prolifération d''algues qui contamine ensuite tout le bassin.', 'débordement, miroir, bac tampon, goulotte');
INSERT INTO procedures (id, owner_id, created_by, type, title, category, summary, content, tags) VALUES (71, 1, 1, 'information', 'Piscine naturelle / biologique : principe et entretien', 'Équipements', 'Une filtration par les plantes et les bactéries, sans chlore.', 'Une piscine naturelle (ou biologique) fonctionne sans traitement chimique : elle repose sur le principe du lagunage, avec une zone de baignade et une zone de régénération (lagunage) où plantes aquatiques et micro-organismes assurent l''épuration de l''eau.
L''eau circule en permanence entre les deux zones grâce à une pompe, imitant le fonctionnement d''un écosystème naturel.
L''entretien reste nécessaire mais différent d''un bassin classique : vidage régulier des skimmers, aspiration ou retrait manuel des algues sur les galets et parois, nettoyage du fond environ une fois par semaine, et surtout entretien de la zone plantée (taille, retrait des plantes mortes) pour garantir l''efficacité de la filtration biologique.
L''équilibre de ce type de bassin est plus lent à s''installer (souvent une saison complète) mais, une fois stabilisé, demande moins de gestes chimiques qu''une piscine traditionnelle.', 'piscine naturelle, biologique, lagunage, sans chlore');
INSERT INTO procedures (id, owner_id, created_by, type, title, category, summary, content, tags) VALUES (72, 1, 2, 'information', 'Robot électrique vs robot hydraulique : comparatif', 'Équipements', 'Autonomie, capacités de nettoyage et entretien : deux logiques différentes.', 'Robot hydraulique : se raccorde à la prise balai ou au skimmer, fonctionne grâce au débit d''eau généré par la pompe de filtration existante. Nettoie principalement le fond (rarement les parois). Peu de composants électroniques donc grande fiabilité mécanique, mais sollicite davantage le préfiltre et le filtre du bassin qu''il faut nettoyer plus souvent.
Robot électrique : totalement autonome, se branche simplement sur une prise électrique (ou fonctionne sur batterie), possède son propre système d''aspiration et de filtration embarqué. Nettoie fond, parois et parfois ligne d''eau en 1h30 à 2h. Entretien limité au nettoyage du filtre/des brosses après chaque cycle, mais coût d''achat nettement plus élevé et plus de composants électroniques pouvant tomber en panne.
Le choix dépend du budget, du niveau d''exigence de propreté recherché et de la sollicitation acceptable du système de filtration existant.', 'robot électrique, robot hydraulique, comparatif, prise balai');
INSERT INTO procedures (id, owner_id, created_by, type, title, category, summary, content, tags) VALUES (73, 1, 1, 'information', 'Formule précise de dosage du chlore choc', 'Calculs & formules', 'La règle des 20 g/m³, et comment l''ajuster.', 'Formule générale : dose (kg) = volume du bassin (m³) × concentration visée (ppm) ÷ concentration du produit (%).
Règle simplifiée couramment utilisée par les professionnels : environ 20 g de chlore choc par m³ pour un traitement standard, ce qui vise environ 5 ppm (5 mg/L) de chlore libre actif dans l''eau — suffisant pour éliminer algues, bactéries et virus.
En cas d''eau très verte, très trouble, ou après une forte fréquentation ponctuelle (fête, forte chaleur), le dosage peut être ponctuellement monté à 25-30 g/m³, en recontrôlant impérativement le taux de chlore avant toute nouvelle baignade.
Rappel indispensable : le choc n''est pleinement efficace que si le pH est préalablement ramené entre 7.2 et 7.4, et la filtration doit tourner en continu pendant au moins 24h après l''application.', 'chlore choc, dosage, formule, ppm, g/m3');
INSERT INTO procedures (id, owner_id, created_by, type, title, category, summary, content, tags) VALUES (74, 3, 3, 'information', 'Réglementation du rejet des eaux de vidange', 'Réglementation & sécurité', 'Un rejet mal préparé est une infraction et un risque environnemental.', 'Le rejet des eaux de vidange d''un bassin dans le réseau collectif d''eaux usées est en principe interdit (article R.1331-2 du Code de la santé publique), sauf dérogation accordée par le service d''assainissement si la capacité de ses ouvrages le permet sans nuire au milieu récepteur — une autorisation préalable doit donc être demandée.
Le rejet sauvage dans la nature (cours d''eau, fossé) est interdit par l''article L211-2 du Code de l''environnement.
Quand elle est possible, l''évacuation se fait de préférence par infiltration dans le sol, via un puits de décantation, après neutralisation complète du chlore.
Précaution essentielle : arrêter tout traitement au chlore au moins 15 jours avant la vidange pour laisser le temps aux résidus de se neutraliser naturellement et protéger la faune/flore aquatique du milieu récepteur.', 'vidange, rejet eau, réglementation environnementale, neutralisation');
INSERT INTO procedures (id, owner_id, created_by, type, title, category, summary, content, tags) VALUES (75, 3, 4, 'information', 'Stockage du chlore : risques d''incendie et cadre ICPE', 'Réglementation & sécurité', 'Le chlore est un comburant : mal stocké, il peut provoquer un incendie ou une explosion.', 'Les produits chlorés de traitement de piscine présentent un risque chimique spécifique (incendie, dégagement de gaz toxiques) renforcé depuis les évolutions réglementaires de janvier 2020 sur le stockage des produits de traitement de l''eau.
Certains produits chlorés peuvent libérer du trichlorure d''azote en cas de mélange accidentel ou d''humidification, en quantité suffisante pour déclencher un incendie voire une explosion.
Pour un stockage de chlore gazeux en grande quantité (installations collectives), le cadre ICPE impose une déclaration à partir de 100 kg et une autorisation à partir de 500 kg de capacité totale.
Règles de base pour tout local technique : ne jamais stocker de matières combustibles à proximité du chlore, local clos, aéré, à l''abri du soleil et d''une température ambiante ne dépassant pas 50°C, produits toujours dans leur emballage d''origine étiqueté.', 'stockage chlore, ICPE, risque incendie, comburant, trichlorure d''azote');
INSERT INTO procedures (id, owner_id, created_by, type, title, category, summary, content, tags) VALUES (76, 1, 1, 'information', 'Inhalation de chlore : symptômes et premiers secours', 'Réglementation & sécurité', 'Réagir vite et bien en cas d''exposition accidentelle en local technique.', 'Symptômes d''une exposition au chlore : picotements de gorge, toux, sensation d''étouffement, maux de tête, larmoiement, irritation cutanée et oculaire, douleurs thoraciques dans les cas plus sérieux.
Premiers gestes : évacuer immédiatement la victime à l''air frais, si possible en hauteur (le chlore gazeux est plus lourd que l''air et stagne au sol), et la mettre au repos sans la faire marcher inutilement.
Retirer les vêtements contaminés et laver abondamment les zones de peau exposées.
En cas de projection dans les yeux : rincer abondamment à l''eau tiède pendant plusieurs minutes.
Il n''existe pas de traitement spécifique à l''inhalation de chlore : appeler les secours (15 ou 112) en cas de symptômes respiratoires marqués ou persistants, une prise en charge médicale peut être nécessaire.', 'inhalation chlore, intoxication, premiers secours, urgence');
INSERT INTO procedures (id, owner_id, created_by, type, title, category, summary, content, tags) VALUES (77, 1, 2, 'information', 'Identifier et comprendre les taches métalliques (fer, cuivre, manganèse)', 'Algues & pathologies de l''eau', 'La couleur de l''eau ou des taches oriente directement le diagnostic.', 'Eau verte translucide (à ne pas confondre avec des algues) : signe de présence de cuivre, souvent lié à la corrosion de canalisations en cuivre ou d''une cellule d''électrolyse en fin de vie.
Teinte rouille ou brune : présence de fer, fréquente sur les eaux de forage ou de puits utilisées pour le remplissage.
Nuances noires en dépôt : présence de manganèse.
Ces métaux, une fois oxydés (notamment après un choc chlore mal anticipé), précipitent et se déposent sous forme de taches sur les parois, le fond et les équipements — d''où l''importance de traiter les métaux avec un séquestrant avant tout traitement choc plutôt qu''après.', 'taches métalliques, fer, cuivre, manganèse, diagnostic couleur eau');
INSERT INTO procedures (id, owner_id, created_by, type, title, category, summary, content, tags) VALUES (78, 1, 1, 'information', 'La caisse à outils du pisciniste : le matériel indispensable', 'Calendrier & organisation', 'Regrouper le nécessaire dans une caisse dédiée fait gagner un temps précieux à chaque intervention.', 'Analyse de l''eau : testeur à pastilles DPD (voire photomètre électronique), bandelettes de dépannage, réactifs de rechange non périmés.
Nettoyage : épuisette de surface, brosse pour parois (adaptée au revêtement), balai aspirateur manuel, éponge/pierre à récurer pour la ligne d''eau.
Produits : pH+, pH-, chlore choc, rehausseur/réducteur de TAC, floculant, séquestrant métaux — en quantités adaptées à la tournée du jour.
Petit outillage technique : tournevis, pince, joints toriques de rechange, graisse silicone, ruban téflon, clé de vidange de filtre.
Protection individuelle : gants résistants aux produits chimiques, lunettes de protection, indispensables dès qu''un produit concentré est manipulé.
Suivi : carnet de suivi ou application mobile pour consigner les relevés et interventions à chaque passage.', 'caisse à outils, matériel professionnel, équipement pisciniste');

-- Fin du seed démo