-- ============================================================
-- SEED DÉMO Piscine Max (multi-tenant) — mot de passe : piscine
-- Réinitialise toutes les données de démonstration.
-- ============================================================
DELETE FROM photos;
DELETE FROM maintenance_logs;
DELETE FROM maintenances;
DELETE FROM pool_seasons;
DELETE FROM pools;
DELETE FROM clients;
DELETE FROM pro_workers;
DELETE FROM users;
DELETE FROM sqlite_sequence WHERE name IN ('users','clients','pools','maintenances','maintenance_logs','pro_workers','photos','pool_seasons');

INSERT INTO users (id, email, password_hash, name, role, color, company, phone, created_by) VALUES (1, 'franck@piscine-max.fr', 'pbkdf2$100000$deab46e50e7ef5ae13717d9478e9bb6b$7b5b49d6b6ea45943d14c79300236cf57cb468affe432d4bcb170322af82f787', 'Franck', 'member', '#0891b2', 'Piscine Max', '06 12 34 56 78', NULL);
INSERT INTO users (id, email, password_hash, name, role, color, company, phone, created_by) VALUES (2, 'romain@piscine-max.fr', 'pbkdf2$100000$be934b28b1f6e02c8e1502b5446754c2$1ea16f4e54d49171918e67851a41b6c0f20e8297d0c9434559b709cdf857901b', 'Romain', 'member', '#16a34a', NULL, '06 98 76 54 32', 1);
INSERT INTO users (id, email, password_hash, name, role, color, company, phone, created_by) VALUES (3, 'sophie@aquazur.fr', 'pbkdf2$100000$8c00efab85c89ca511b1c1345e59c1bb$b6fb11d17b2aba26a90bafe1702041fd1f89dfb2a0c413fed2b4c62ab32d406c', 'Sophie Marin', 'member', '#8b5cf6', 'AquaZur', '06 11 22 33 44', NULL);
INSERT INTO users (id, email, password_hash, name, role, color, company, phone, created_by) VALUES (4, 'leo@aquazur.fr', 'pbkdf2$100000$08e781d884f1b800a5aa1bfe7d617acc$dbf187feb7e1a279bbff97725466fc8963d643d43264b1dae7da3bebb726b0d5', 'Léo', 'member', '#f59e0b', NULL, '06 55 66 77 88', 3);
INSERT INTO users (id, email, password_hash, name, role, color, company, phone, created_by) VALUES (5, 'client1@piscine-max.fr', 'pbkdf2$100000$99a76bd45fbc6ec5ec3259921151eaa8$bafc04977af17f5cdc79d9e89008fb90aa6e2ba5a9322b01dbe37a864f6df366', 'Famille Dubois', 'client', '#64748b', NULL, NULL, 1);
INSERT INTO users (id, email, password_hash, name, role, color, company, phone, created_by) VALUES (6, 'client2@piscine-max.fr', 'pbkdf2$100000$e95244c235aa1884dadca8cbca9308c6$7d352fac91b46008aba5acd4064fbc775a92ede1d8831942583352b6d7030ad9', 'M. Lefevre', 'client', '#64748b', NULL, NULL, 1);

INSERT INTO pro_workers (pro_id, worker_id) VALUES (1, 2);  -- Romain bosse pour Franck
INSERT INTO pro_workers (pro_id, worker_id) VALUES (3, 4);  -- Léo bosse pour Sophie
INSERT INTO pro_workers (pro_id, worker_id) VALUES (3, 2);  -- Romain bosse AUSSI pour Sophie (un user, 2 employeurs)

INSERT INTO clients (id, name, phone, email, notes, owner_id, client_user_id) VALUES (1, 'Famille Dubois', '06 20 11 22 33', 'client1@piscine-max.fr', 'Maison avec grand portail bleu. Sonner 2 fois.', 1, 5);
INSERT INTO clients (id, name, phone, email, notes, owner_id, client_user_id) VALUES (2, 'M. Lefevre', '06 30 44 55 66', 'client2@piscine-max.fr', 'Résidence secondaire, présent surtout l''été.', 1, 6);
INSERT INTO clients (id, name, phone, email, notes, owner_id, client_user_id) VALUES (3, 'Villa Les Mimosas', '04 94 00 11 22', 'contact@lesmimosas.fr', 'Location saisonnière, 2 piscines à entretenir.', 1, NULL);
INSERT INTO clients (id, name, phone, email, notes, owner_id, client_user_id) VALUES (4, 'Restaurant La Plage', '04 94 33 44 55', 'resa@laplage.fr', 'Piscine du restaurant, entretien tôt le matin avant ouverture.', 1, NULL);
INSERT INTO clients (id, name, phone, email, notes, owner_id, client_user_id) VALUES (5, 'M. et Mme Garcia', '06 77 88 99 00', 'garcia@exemple.fr', 'Client de Sophie.', 3, NULL);
INSERT INTO clients (id, name, phone, email, notes, owner_id, client_user_id) VALUES (6, 'Camping Le Pin', '04 94 99 88 77', 'camping@lepin.fr', 'Grande piscine collective.', 3, NULL);

INSERT INTO pools (id, client_id, owner_id, label, address, lat, lng, pool_type, volume_m3, shape, treatment_type, filtration_type, access_code, access_notes, routine, routine_client, ideal_ph_min, ideal_ph_max, ideal_chlorine_min, ideal_chlorine_max, priority, ideal_salt_min, ideal_salt_max, ideal_tac_min, ideal_tac_max, ideal_stabilizer_min, ideal_stabilizer_max, depth_avg_m, expected_interval_days) VALUES (1, 1, 1, 'Piscine principale', '12 Chemin des Oliviers, 83110 Sanary-sur-Mer', 43.1287, 5.8011, 'enterrée', 48, 'rectangulaire', 'sel/électrolyse', 'sable', 'B1234', 'Portail bleu, local technique au fond du jardin à droite. Chien gentil.', '["Vérifier le niveau d''eau","Nettoyer les skimmers et le préfiltre","Tester pH et chlore","Brosser les parois","Contrôler la pression du filtre"]', 'Passez le robot 1 à 2 fois par semaine. Maintenez le niveau d''eau à la moitié des skimmers. Évitez de vous baigner dans les 4h après un ajout de produit.', 7, 7.4, 1, 2, 1, 3.0, 5.0, 80, 120, 30, 50, 1.5, 7);
INSERT INTO pools (id, client_id, owner_id, label, address, lat, lng, pool_type, volume_m3, shape, treatment_type, filtration_type, access_code, access_notes, routine, routine_client, ideal_ph_min, ideal_ph_max, ideal_chlorine_min, ideal_chlorine_max, priority, ideal_salt_min, ideal_salt_max, ideal_tac_min, ideal_tac_max, ideal_stabilizer_min, ideal_stabilizer_max, depth_avg_m, expected_interval_days) VALUES (2, 2, 1, 'Piscine', '45 Avenue de la Mer, 83140 Six-Fours-les-Plages', 43.0942, 5.8389, 'coque', 32, 'haricot', 'chlore', 'cartouche', '', 'Clé sous le pot de fleurs près de la porte de garage.', '["Tester pH et chlore","Nettoyer la ligne d''eau","Vider les paniers"]', 'Surveillez la couleur de l''eau. En cas d''eau trouble, appelez-moi.', 7, 7.4, 1.5, 3, 0, 3.0, 5.0, 80, 120, 30, 50, 1.5, 7);
INSERT INTO pools (id, client_id, owner_id, label, address, lat, lng, pool_type, volume_m3, shape, treatment_type, filtration_type, access_code, access_notes, routine, routine_client, ideal_ph_min, ideal_ph_max, ideal_chlorine_min, ideal_chlorine_max, priority, ideal_salt_min, ideal_salt_max, ideal_tac_min, ideal_tac_max, ideal_stabilizer_min, ideal_stabilizer_max, depth_avg_m, expected_interval_days) VALUES (3, 3, 1, 'Grande piscine', '8 Route de Bandol, 83150 Bandol', 43.1355, 5.7531, 'béton', 75, 'rectangulaire', 'sel/électrolyse', 'sable', 'C5678', 'Code portail C5678. Piscine côté terrasse.', '["Analyse complète de l''eau","Nettoyage robot","Backwash filtre","Contrôle électrolyseur"]', '', 7.2, 7.6, 1, 2, 1, 3.0, 5.0, 80, 120, 30, 50, 1.5, 7);
INSERT INTO pools (id, client_id, owner_id, label, address, lat, lng, pool_type, volume_m3, shape, treatment_type, filtration_type, access_code, access_notes, routine, routine_client, ideal_ph_min, ideal_ph_max, ideal_chlorine_min, ideal_chlorine_max, priority, ideal_salt_min, ideal_salt_max, ideal_tac_min, ideal_tac_max, ideal_stabilizer_min, ideal_stabilizer_max, depth_avg_m, expected_interval_days) VALUES (4, 3, 1, 'Petit bassin', '8 Route de Bandol, 83150 Bandol', 43.1358, 5.7535, 'béton', 18, 'carrée', 'chlore', 'cartouche', 'C5678', 'Même accès que la grande piscine.', '["Tester pH et chlore","Nettoyer le bassin"]', '', 7, 7.4, 1, 2, 0, 3.0, 5.0, 80, 120, 30, 50, 1.5, 7);
INSERT INTO pools (id, client_id, owner_id, label, address, lat, lng, pool_type, volume_m3, shape, treatment_type, filtration_type, access_code, access_notes, routine, routine_client, ideal_ph_min, ideal_ph_max, ideal_chlorine_min, ideal_chlorine_max, priority, ideal_salt_min, ideal_salt_max, ideal_tac_min, ideal_tac_max, ideal_stabilizer_min, ideal_stabilizer_max, depth_avg_m, expected_interval_days) VALUES (5, 4, 1, 'Piscine restaurant', '2 Promenade du Front de Mer, 83110 Sanary-sur-Mer', 43.1201, 5.7998, 'enterrée', 60, 'libre', 'sel/électrolyse', 'verre', 'RESTO', 'Entrée par l''arrière, avant 9h. Demander au gérant.', '["Analyse eau","Nettoyage complet","Vérifier propreté plages"]', '', 7, 7.4, 1.5, 2.5, 1, 3.0, 5.0, 80, 120, 30, 50, 1.5, 7);
INSERT INTO pools (id, client_id, owner_id, label, address, lat, lng, pool_type, volume_m3, shape, treatment_type, filtration_type, access_code, access_notes, routine, routine_client, ideal_ph_min, ideal_ph_max, ideal_chlorine_min, ideal_chlorine_max, priority, ideal_salt_min, ideal_salt_max, ideal_tac_min, ideal_tac_max, ideal_stabilizer_min, ideal_stabilizer_max, depth_avg_m, expected_interval_days) VALUES (6, 5, 3, 'Piscine Garcia', '15 Rue des Lauriers, 83000 Toulon', 43.1242, 5.928, 'enterrée', 40, 'ovale', 'chlore', 'sable', '9012', 'Portail vert.', '["pH chlore","Skimmers"]', '', 7, 7.4, 1, 2, 0, 3.0, 5.0, 80, 120, 30, 50, 1.5, 7);
INSERT INTO pools (id, client_id, owner_id, label, address, lat, lng, pool_type, volume_m3, shape, treatment_type, filtration_type, access_code, access_notes, routine, routine_client, ideal_ph_min, ideal_ph_max, ideal_chlorine_min, ideal_chlorine_max, priority, ideal_salt_min, ideal_salt_max, ideal_tac_min, ideal_tac_max, ideal_stabilizer_min, ideal_stabilizer_max, depth_avg_m, expected_interval_days) VALUES (7, 6, 3, 'Piscine camping', '100 Route des Pins, 83270 Saint-Cyr-sur-Mer', 43.18, 5.71, 'béton', 120, 'rectangulaire', 'sel/électrolyse', 'sable', 'CAMP', 'Voir réception.', '["Analyse","Robot","Backwash"]', '', 7.2, 7.6, 1.5, 3, 1, 3.0, 5.0, 80, 120, 30, 50, 1.5, 7);

INSERT INTO maintenances (id, pool_id, assigned_to, kind, weekday, interval_weeks, start_date, time, duration_min, notes) VALUES (1, 1, 2, 'recurring', 2, 1, '2025-01-01', '09:00', 45, 'Entretien hebdo');
INSERT INTO maintenances (id, pool_id, assigned_to, kind, weekday, interval_weeks, start_date, time, duration_min, notes) VALUES (2, 2, 1, 'recurring', 3, 2, '2025-01-01', '10:30', 30, 'Toutes les 2 semaines');
INSERT INTO maintenances (id, pool_id, assigned_to, kind, weekday, interval_weeks, start_date, time, duration_min, notes) VALUES (3, 3, 2, 'recurring', 2, 1, '2025-01-01', '11:00', 60, '');
INSERT INTO maintenances (id, pool_id, assigned_to, kind, weekday, interval_weeks, start_date, time, duration_min, notes) VALUES (4, 4, 2, 'recurring', 2, 1, '2025-01-01', '12:15', 20, 'Juste après la grande');
INSERT INTO maintenances (id, pool_id, assigned_to, kind, weekday, interval_weeks, start_date, time, duration_min, notes) VALUES (5, 5, 1, 'recurring', 5, 1, '2025-01-01', '07:30', 45, 'Avant ouverture resto');
INSERT INTO maintenances (id, pool_id, assigned_to, kind, oneshot_date, time, duration_min, notes) VALUES (6, 1, 1, 'oneshot', '2026-07-03', '14:00', 60, 'Hivernage');
INSERT INTO maintenances (id, pool_id, assigned_to, kind, weekday, interval_weeks, start_date, time, duration_min, notes) VALUES (7, 6, 4, 'recurring', 1, 1, '2025-01-01', '09:00', 30, '');
INSERT INTO maintenances (id, pool_id, assigned_to, kind, weekday, interval_weeks, start_date, time, duration_min, notes) VALUES (8, 7, 4, 'recurring', 4, 1, '2025-01-01', '08:00', 90, '');

INSERT INTO pool_seasons (pool_id, label, start_md, end_md, interval_days, weekday, sort_order, active) VALUES (1, 'Haute saison', '06-01', '09-15', 3, NULL, 0, 1);
INSERT INTO pool_seasons (pool_id, label, start_md, end_md, interval_days, weekday, sort_order, active) VALUES (1, 'Mi-saison', '04-01', '05-31', 7, NULL, 1, 1);
INSERT INTO pool_seasons (pool_id, label, start_md, end_md, interval_days, weekday, sort_order, active) VALUES (1, 'Automne', '09-16', '10-31', 7, NULL, 2, 1);
INSERT INTO pool_seasons (pool_id, label, start_md, end_md, interval_days, weekday, sort_order, active) VALUES (1, 'Hivernage', '11-01', '03-31', 30, NULL, 3, 1);
INSERT INTO pool_seasons (pool_id, label, start_md, end_md, interval_days, weekday, sort_order, active) VALUES (5, 'Pleine saison resto', '05-15', '09-30', 2, NULL, 0, 1);
INSERT INTO pool_seasons (pool_id, label, start_md, end_md, interval_days, weekday, sort_order, active) VALUES (5, 'Hors saison', '10-01', '05-14', 14, NULL, 1, 1);

INSERT INTO maintenance_logs (id, maintenance_id, done_by, done_date, status, ph, chlorine, salt, water_temp, stabilizer, tac, products_added, notes, duration_min) VALUES (1, 1, 2, '2026-05-03', 'done', 7.6, 0.4, 4.2, 27, 35, 110, 'pH- 1L, chlore choc 500g', 'pH un peu haut, corrigé', 45);
INSERT INTO maintenance_logs (id, maintenance_id, done_by, done_date, status, ph, chlorine, salt, water_temp, stabilizer, tac, products_added, notes, duration_min) VALUES (2, 1, 2, '2026-05-10', 'done', 7.5, 0.6, 4.1, 27, 35, 105, 'pH- 0.5L', 'RAS', 45);
INSERT INTO maintenance_logs (id, maintenance_id, done_by, done_date, status, ph, chlorine, salt, water_temp, stabilizer, tac, products_added, notes, duration_min) VALUES (3, 1, 2, '2026-05-17', 'done', 7.3, 1.2, 4, 26, 32, 100, NULL, 'Eau nickel', 45);
INSERT INTO maintenance_logs (id, maintenance_id, done_by, done_date, status, ph, chlorine, salt, water_temp, stabilizer, tac, products_added, notes, duration_min) VALUES (4, 1, 2, '2026-05-24', 'done', 7.2, 1.5, 4, 26, 30, 100, NULL, 'RAS', 45);
INSERT INTO maintenance_logs (id, maintenance_id, done_by, done_date, status, ph, chlorine, salt, water_temp, stabilizer, tac, products_added, notes, duration_min) VALUES (5, 1, 2, '2026-05-31', 'done', 7.2, 1.6, 3.9, 25, 30, 98, NULL, 'Filtre nettoyé', 45);
INSERT INTO maintenance_logs (id, maintenance_id, done_by, done_date, status, ph, chlorine, salt, water_temp, stabilizer, tac, products_added, notes, duration_min) VALUES (6, 1, 2, '2026-06-07', 'done', 7.1, 1.8, 4, 24, 28, 95, NULL, 'RAS', 45);
INSERT INTO maintenance_logs (id, maintenance_id, done_by, done_date, status, ph, chlorine, salt, water_temp, stabilizer, tac, products_added, notes, duration_min) VALUES (7, 1, 2, '2026-06-14', 'done', 7.2, 1.7, 4, 23, 30, 100, NULL, 'RAS', 45);
INSERT INTO maintenance_logs (id, maintenance_id, done_by, done_date, status, ph, chlorine, salt, water_temp, stabilizer, tac, products_added, notes, duration_min) VALUES (8, 1, 2, '2026-06-25', 'done', 7.9, 0.4, 4, 29, 30, 100, NULL, 'Forte chaleur, chlore consommé — à resurveiller', 45);
INSERT INTO maintenance_logs (id, maintenance_id, done_by, done_date, status, ph, chlorine, salt, water_temp, stabilizer, tac, products_added, notes, duration_min) VALUES (9, 3, 2, '2026-05-31', 'done', 7.8, 0.8, 4.5, 27, 40, 120, 'pH- 2L', 'pH haut', 45);
INSERT INTO maintenance_logs (id, maintenance_id, done_by, done_date, status, ph, chlorine, salt, water_temp, stabilizer, tac, products_added, notes, duration_min) VALUES (10, 3, 2, '2026-06-07', 'done', 7.5, 1.4, 4.3, 26, 38, 110, NULL, 'RAS', 45);
INSERT INTO maintenance_logs (id, maintenance_id, done_by, done_date, status, ph, chlorine, salt, water_temp, stabilizer, tac, products_added, notes, duration_min) VALUES (11, 3, 2, '2026-06-14', 'done', 7.4, 1.6, 4.2, 25, 35, 105, NULL, 'RAS', 45);
INSERT INTO maintenance_logs (id, maintenance_id, done_by, done_date, status, ph, chlorine, salt, water_temp, stabilizer, tac, products_added, notes, duration_min) VALUES (12, 3, 2, '2026-06-21', 'done', 7.3, 1.8, 4.2, 24, 35, 100, NULL, 'Backwash effectué', 45);
INSERT INTO maintenance_logs (id, maintenance_id, done_by, done_date, status, ph, chlorine, salt, water_temp, stabilizer, tac, products_added, notes, duration_min) VALUES (13, 2, 1, '2026-06-18', 'done', 7.3, 1.5, NULL, 25, 30, 90, NULL, 'RAS', 45);
INSERT INTO maintenance_logs (id, maintenance_id, done_by, done_date, status, ph, chlorine, salt, water_temp, stabilizer, tac, products_added, notes, duration_min) VALUES (14, 2, 1, '2026-06-04', 'done', 7.4, 1.2, NULL, 24, 30, 90, 'Chlore lent 1kg', 'Recharge galets', 45);

-- Fin du seed démo